// src/views/pages/device/product/save/index.vue
<template>
  <a-drawer title="新增产品" v-model:visible="modalVisible" @close="closeBtn" :width="450">
    <a-form :model="form" :rules="rules" layout="vertical">
      <a-form-item label="图标" name="photoUrl">
        <FormUpload v-model="form.photoUrl" />
      </a-form-item>
      <a-form-item label="产品ID" name="id">
        <a-input v-model:value="form.id" placeholder="请输入" />
      </a-form-item>
      <a-form-item label="产品名称" name="name">
        <a-input v-model:value="form.name" placeholder="请输入"
        />
      </a-form-item>
      <a-form-item label="所属品类" name="classifiedId">
        <a-tree-select
          :treeDefaultExpandedKeys="[form.classifiedId]"
          v-model:value="form.classifiedId"
          style="width: 100%"
          :dropdown-style="{ maxHeight: '400px', overflow: 'auto' }"
          :tree-data="categoryList"
          placeholder="请选择"
        ></a-tree-select>
      </a-form-item>
      <a-form-item label="所属机构" name="orgId">
        <a-tree-select
          v-model:value="form.orgId"
          style="width: 100%"
          :dropdown-style="{ maxHeight: '400px', overflow: 'auto' }"
          :tree-data="orgList"
          placeholder="请选择"
        ></a-tree-select>
      </a-form-item>
      <a-form-item label="消息协议" name="messageProtocol">
        <a-select placeholder="请选择" v-model:value="form.messageProtocol">
          <template v-for="item in messageProtocolList" :key="item.id">
            <a-select-option :value="item.id">{{ item.name }}</a-select-option>
          </template>
        </a-select>
      </a-form-item>
      <a-form-item label="传输协议" name="transportProtocol">
        <a-select placeholder="请选择" v-model:value="form.transportProtocol">
          <template v-for="item in transportsList" :key="item.id">
            <a-select-option :value="item.id">{{ item.name }}</a-select-option>
          </template>
        </a-select>
      </a-form-item>
      <a-form-item label="存储策略" name="storePolicy">
        <a-select placeholder="请选择" v-model:value="form.storePolicy">
          <template v-for="item in storageList" :key="item.id">
            <a-select-option  :value="item.id">{{ item.name }}</a-select-option>
          </template>
        </a-select>
      </a-form-item>
      <a-form-item label="设备类型" name="deviceType">
        <a-radio-group v-model:value="form.deviceType">
          <a-radio value="device">直连设备</a-radio>
          <a-radio value="childrenDevice">网关子设备</a-radio>
          <a-radio value="gateway">网关设备</a-radio>
        </a-radio-group>
      </a-form-item>
      <a-form-item label="描述" name="describe">
        <a-textarea
          v-model:value="form.describe"
          :rows="4"
          placeholder="请输入"
        />
      </a-form-item>
    </a-form>
    <div
      :style="{
        position: 'absolute',
        right: 0,
        bottom: 0,
        width: '100%',
        borderTop: '1px solid #e9e9e9',
        padding: '10px 16px',
        background: '#fff',
        textAlign: 'right',
        zIndex: 1,
      }"
    >
      <a-button style="margin-right: 8px" @click="closeBtn">取消</a-button>
      <a-button type="primary" @click="okBtn">确定</a-button>
    </div>
  </a-drawer>
</template>

<script lang="ts">
import { defineComponent, ref, watchEffect, reactive, watch, toRefs, toRaw } from 'vue'
import { getStorageList, getMessageProtocolList, getTransportsList, getOrgList, getCategory, getDefaultModel } from '../service'
import encodeQuery from '@/utils/encodeQuery'
import FormUpload from '@/components/FormUpload/index.vue'
import { getView } from '@/utils/utils'
export default defineComponent({
  name: 'Save',
  props: ['modelValue', 'data'],
  emits: ['update:modelValue', 'ok-btn'],
  components: { FormUpload },
  setup (props, { emit }) {
    const modalVisible = ref<boolean>(false)
    const storageList = reactive<any[]>([])
    const messageProtocolList = reactive<any[]>([])
    const transportsList = reactive<any[]>([])
    const orgList = reactive<any[]>([])
    const defaultMetadata = ref<string>(props.data.metadata || '{"events":[],"properties":[],"functions":[],"tags":[]}')
    const categoryList = reactive<any[]>([])
    const form = reactive({
      id: '',
      name: '',
      classifiedId: '',
      classifiedName: '',
      photoUrl: 'https://demo.jetlinks.cn/static/product.1bd0a3b1.png',
      deviceType: '',
      messageProtocol: '',
      orgId: '',
      protocolName: '',
      storePolicy: '',
      transportProtocol: '',
      describe: ''
    })
    const rules = {
      id: [{ required: true, message: '请输入' }],
      name: [{ required: true, message: '请输入' }],
      classifiedId: [{ required: true, message: '请输入' }],
      messageProtocol: [{ required: true, message: '请选择' }],
      transportProtocol: [{ required: true, message: '请选择' }],
      deviceType: [{ required: true, message: '请选择' }]
    }
    const getDefaultMetadata = (id: string, transport: string) => {
      getDefaultModel(id, transport).then(resp => {
        if (resp.data.status === 200) {
          if (resp.data.result === '{}') {
            defaultMetadata.value = '{"events":[],"properties":[],"functions":[],"tags":[]}'
          } else {
            defaultMetadata.value = resp.data.result
          }
        } else {
          defaultMetadata.value = '{"events":[],"properties":[],"functions":[],"tags":[]}'
        }
      })
    }
    watchEffect(() => {
      Object.assign(form, props.data)
    })
    watch(() => props.modelValue, (newValue) => {
      modalVisible.value = newValue
      if (newValue) {
        // 机构
        getOrgList(encodeQuery({
          paging: false,
          terms: {
            typeId: 'org'
          }
        })).then(resp => {
          if (resp.data.status === 200) {
            const list = resp.data.result.map((i: any) => {
              return { ...getView(i) }
            })
            Object.assign(orgList, list)
          }
        })
        // 存储策略
        getStorageList().then(resp => {
          if (resp.data.status === 200) {
            Object.assign(storageList, resp.data.result)
          }
        })
        // 消息协议
        getMessageProtocolList().then(resp => {
          if (resp.data.status === 200) {
            Object.assign(messageProtocolList, resp.data.result)
          }
        })
        // 产品分类
        getCategory({ paging: false }).then(resp => {
          const list = resp.data.result.map((i: any) => {
            return { ...getView(i) }
          })
          Object.assign(categoryList, list)
        })
      }
    })
    watch(() => form.messageProtocol, (newValue) => {
      if (newValue) { // 传输协议
        getTransportsList(newValue).then(resp => {
          if (resp.data.status === 200) {
            Object.assign(transportsList, resp.data.result)
            if (newValue === props.data.messageProtocol) {
              form.transportProtocol = props.data.transportProtocol
            } else {
              form.transportProtocol = ''
            }
          }
        })
      }
    })
    watch(() => form.transportProtocol, (newValue) => {
      if (newValue !== '' && form.messageProtocol !== '' && props.data.id !== '') {
        getDefaultMetadata(form.messageProtocol, newValue)
      }
    })
    const getTreeNode = (tree: any[], str: string) => {
      for (const data of tree) {
        if (data.value === str) return data
        if (data.children) {
          const res:any = getTreeNode(data.children, str)
          if (res) return res
        }
      }
      return null
    }
    const okBtn = () => {
      const protocol = messageProtocolList.find(item => form.messageProtocol === item.id)
      const classified = getTreeNode(categoryList, form.classifiedId)
      const data = {
        ...toRaw(form),
        metadata: defaultMetadata.value,
        protocolName: protocol.name,
        classifiedName: classified ? classified.title : ''
      }
      emit('ok-btn', data)
      modalVisible.value = false
      emit('update:modelValue', false)
    }
    const closeBtn = () => {
      modalVisible.value = false
      emit('update:modelValue', false)
    }
    return {
      form,
      rules,
      modalVisible,
      okBtn,
      storageList,
      messageProtocolList,
      transportsList,
      orgList,
      categoryList,
      closeBtn
    }
  }
})
</script>

// src/pages/device/product/save/index.tsx
import React, {useEffect, useState} from 'react';
import {FormComponentProps} from 'antd/lib/form';
import Form from 'antd/es/form';
import {Avatar, Button, Card, Col, Drawer, Input, message, Radio, Row, Select, TreeSelect, Upload} from 'antd';
import {DeviceProduct} from '../data';
import {FormItemConfig} from '@/utils/common';
import apis from '@/services';
import styles from "@/pages/device/product/save/style.less";
import productImg from "@/pages/device/product/img/product.png";
import {UploadProps} from "antd/lib/upload";
import {getAccessToken} from "@/utils/authority";
import {UploadOutlined} from "@ant-design/icons/lib";
import {ProtocolItem} from "@/pages/device/protocol/data";

interface Props extends FormComponentProps {
  data?: Partial<DeviceProduct>;
  close: Function;
  save: (data: Partial<DeviceProduct>) => void;
}

interface State {
  protocolSupports: any[];
  protocolTransports: any[];
  organizationList: any[];
  configName: string;
}

const Save: React.FC<Props> = props => {
  const initState: State = {
    protocolSupports: [],
    protocolTransports: [],
    organizationList: [],
    categoryLIst: [],
  };

  const {getFieldDecorator} = props.form;
  // 消息协议
  const [protocolSupports, setProtocolSupports] = useState(initState.protocolSupports);
  // 消息协议
  const [organizationList, setOrganizationList] = useState(initState.organizationList);
  // 传输协议
  const [protocolTransports, setProtocolTransports] = useState(initState.protocolTransports);

  const [categoryLIst, setCategoryLIst] = useState(initState.categoryLIst);

  const [photoUrl, setPhotoUrl] = useState(props.data?.photoUrl);

  const onMessageProtocolChange = (value: string) => {
    // 获取链接协议
    apis.deviceProdcut
      .protocolTransports(value)
      .then(e => {
        if (e.status === 200) {
          setProtocolTransports(e.result);
        }
      })
      .catch(() => {
      });
  };

  useEffect(() => {
    apis.deviceProdcut
      .protocolSupport()
      .then(e => {
        if (e.status === 200) {
          setProtocolSupports(e.result);
        }
      })
      .catch(() => {
      });

    apis.deviceProdcut.queryOrganization()
      .then((res: any) => {
        if (res.status === 200) {
          let orgList: any = [];
          res.result.map((item: any) => {
            orgList.push({id: item.id, pId: item.parentId, value: item.id, title: item.name})
          });
          setOrganizationList(orgList);
        }
      }).catch(() => {
    });

    apis.deviceProdcut.deviceCategory()
      .then((response: any) => {
        if (response.status === 200) {
          setCategoryLIst(response.result);
        }
      })
      .catch(() => {
      });

    if (props.data && props.data.messageProtocol) {
      onMessageProtocolChange(props.data.messageProtocol);
    }
  }, []);


  const basicForm: FormItemConfig[] = [
    {
      label: '产品ID',
      key: 'id',
      styles: {
        lg: {span: 8},
        md: {span: 12},
        sm: {span: 24},
      },
      options: {
        initialValue: props.data?.id,
        rules: [{required: true, message: '请输入产品ID'}],
      },

      component: (
        <Input
          placeholder="请输入产品ID "
          disabled={!!props.data?.id}
        />
      ),
    },
    {
      label: '产品名称',
      key: 'name',
      options: {
        rules: [{required: true, message: '请选择产品名称'}],
        initialValue: props.data?.name,
      },
      styles: {
        xl: {span: 8},
        lg: {span: 8},
        md: {span: 12},
        sm: {span: 24},
      },
      component: <Input style={{width: '100%'}} placeholder="请输入"/>,
    },
    {
      label: '所属分类',
      key: 'classified',
      options: {
        initialValue: props.data?.classifiedId,
      },
      styles: {
        xl: {span: 8},
        lg: {span: 8},
        md: {span: 12},
        sm: {span: 24},
      },
      component: (
        <Select disabled>
          {categoryLIst.map((e:any) => (
            <Select.Option value={e.id} key={e.id}>
              {e.name}
            </Select.Option>
          ))}
        </Select>
      ),
    },
    {
      label: '所属机构',
      key: 'orgId',
      options: {
        initialValue: props.data?.orgId,
      },
      styles: {
        xl: {span: 8},
        lg: {span: 10},
        md: {span: 24},
        sm: {span: 24},
      },
      component: <TreeSelect
        allowClear treeDataSimpleMode showSearch
        placeholder="所属机构" treeData={organizationList}
        treeNodeFilterProp='title' searchPlaceholder='根据机构名称模糊查询'
      />,
    },
    {
      label: '消息协议',
      key: 'messageProtocol',
      options: {
        rules: [{required: true, message: '请选择消息协议'}],
        initialValue: props.data?.messageProtocol,
      },
      styles: {
        xl: {span: 8},
        lg: {span: 8},
        md: {span: 12},
        sm: {span: 24},
      },
      component: (
        <Select
          placeholder="请选择"
          onChange={(value: string) => {
            onMessageProtocolChange(value);
          }}
        >
          {protocolSupports.map(e => (
            <Select.Option value={e.id} key={e.id}>
              {e.name}
            </Select.Option>
          ))}
        </Select>
      ),
    },
    {
      label: '传输协议',
      key: 'transportProtocol',
      options: {
        rules: [{required: true, message: '请选择传输协议'}],
        initialValue: props.data?.transportProtocol,
      },
      styles: {
        xl: {span: 8},
        lg: {span: 10},
        md: {span: 24},
        sm: {span: 24},
      },
      component: (
        <Select
          placeholder="请选择">
          {protocolTransports.map(e => (
            <Select.Option value={e.id} key={e.id}>
              {e.name}
            </Select.Option>
          ))}
        </Select>
      ),
    },

    {
      label: '设备类型',
      key: 'deviceType',
      options: {
        rules: [{required: true, message: '请选择设备类型'}],
        initialValue:
          typeof props.data?.deviceType === 'string'
            ? props.data?.deviceType
            : (props.data?.deviceType || {}).value,
      },
      styles: {
        lg: {span: 8},
        md: {span: 12},
        sm: {span: 24},
      },
      component: (
        <Radio.Group>
          <Radio value="device">直连设备</Radio>
          <Radio value="childrenDevice">网关子设备</Radio>
          <Radio value="gateway">网关设备</Radio>
        </Radio.Group>
      ),
    },
    {
      label: '描述',
      key: 'describe',
      styles: {
        xl: {span: 24},
        lg: {span: 24},
        md: {span: 24},
        sm: {span: 24},
      },
      options: {
        initialValue: props.data?.describe,
      },
      component: <Input.TextArea rows={3} placeholder="请输入描述"/>,
    },
  ];

  const saveData = () => {
    const {form} = props;
    form.validateFields((err, fileValue) => {
      if (err) return;
      if (!fileValue.orgId) {
        fileValue.orgId = '';
      }
      const protocol: Partial<ProtocolItem> =
        protocolSupports.find(i => i.id === fileValue.messageProtocol) || {};

      props.save({state: 0, ...fileValue, photoUrl,protocolName: protocol.name});
    });
  };

  const uploadProps: UploadProps = {
    action: '/jetlinks/file/static',
    headers: {
      'X-Access-Token': getAccessToken(),
    },
    showUploadList: false,
    onChange(info) {
      if (info.file.status === 'done') {
        setPhotoUrl(info.file.response.result);
        message.success('上传成功');
      }
    },
  };

  return (
    <Drawer
      visible
      title={`${props.data?.id ? '编辑' : '新增'}产品`}
      width={500}
      onClose={() => props.close()}
      closable
    >
      <Form labelCol={{span: 6}} wrapperCol={{span: 18}}>
        <Card title="基本信息" style={{marginBottom: 20}} bordered={false}>
          <Form.Item label='图标'>
            <>
              <div className={styles.avatar}>
                <Avatar size={80} src={photoUrl || props.data?.photoUrl || productImg}/>
              </div>
              <Upload {...uploadProps} showUploadList={false}>
                <Button>
                  <UploadOutlined/>
                  更换图片
                </Button>
              </Upload>
            </>
          </Form.Item>
          <Row gutter={16}>
            {basicForm.map(item => (
              <Col
                key={item.key}
              >
                <Form.Item label={item.label}>
                  {getFieldDecorator(item.key, item.options)(item.component)}
                </Form.Item>
              </Col>
            ))}
          </Row>
        </Card>
      </Form>

      <div
        style={{
          position: 'absolute',
          right: 0,
          bottom: 0,
          width: '100%',
          borderTop: '1px solid #e9e9e9',
          padding: '10px 16px',
          background: '#fff',
          textAlign: 'right',
        }}
      >
        <Button
          onClick={() => {
            props.close();
          }}
          style={{marginRight: 8}}
        >
          关闭
        </Button>
        <Button
          onClick={() => {
            saveData();
          }}
          type="primary"
        >
          保存
        </Button>
      </div>
    </Drawer>
  );
};

export default Form.create<Props>()(Save);
