// src/views/pages/device/alarm/index.vue
<template>
  <a-tabs tab-position="top" type="card" v-model:activeKey="activeKey" @change="activeChange">
    <a-tab-pane key="1" tab="告警设置">
      <a-card>
        <template #extra>
          <a-button type="primary">新增告警</a-button>
        </template>
        <a-table rowKey="id" :dataSource="dataSource" :columns="columns">
          <template #createTime="slotProps">
            <span>{{ $moment(slotProps.value).format('YYYY-MM-DD HH:mm:ss') }}</span>
          </template>
          <template #state="{ text }">
            <a-badge :color="text.value !== 'stopped' ? 'green' : 'red'" :text="text.text"></a-badge>
          </template>
          <template #operation="{record}">
            <a-space>
              <a>编辑</a>
              <a @click="getAlarmLog(record)">告警日志</a>
              <template v-if="record.state.value === 'stopped'">
                <a @click="startAlarmBtn(record.id)">启动</a>
                <a-popconfirm
                  title="确认删除?"
                  ok-text="确认"
                  cancel-text="取消"
                  @confirm="deleteAlarmBtn(record.id)"
                >
                  <a>删除</a>
                </a-popconfirm>
              </template>
              <a v-else @click="stopAlarmBtn(record.id)">停止</a>
            </a-space>
          </template>
        </a-table>
      </a-card>
    </a-tab-pane>
    <a-tab-pane key="2" tab="告警记录">
      <a-card>
        <template #title>
          <a-select
            v-model:value="value"
            show-search
            placeholder="请选择"
            style="width: 250px"
            :options="options"
            @change="handleChange"
          >
          </a-select>
        </template>
        <a-table
          rowKey="id"
          :dataSource="dataLogSource.data"
          :columns="columnsLog"
          @change="handleTableChange"
          :pagination="{
            pageSize: dataLogSource.pageSize,
            showQuickJumper: false,
            showSizeChanger: false,
            total: dataLogSource.total,
            showTotal: (total) => `共${total}条记录`
          }"
        >
          <template #alarmTime="slotProps">
            <span>{{ $moment(slotProps.value).format('YYYY-MM-DD HH:mm:ss') }}</span>
          </template>
          <template #state="{ text }">
            <template v-if="text === 'solve'">
              <a-tag color="#108ee9">已处理</a-tag>
            </template>
            <template v-else>
              <a-tag color="#f50">未处理</a-tag>
            </template>
          </template>
          <template #operation="{ record }">
            <a-space>
              <a @click="info(record)">详情</a>
              <a v-if="record.state !== 'solve'" @click="solveAlarmLog(record.id)">处理</a>
            </a-space>
          </template>
        </a-table>
      </a-card>
    </a-tab-pane>
  </a-tabs>
  <a-modal v-model:visible="visible" title="告警处理结果" @ok="handleOk" ok-text="确认" cancel-text="取消">
    <a-form ref="formRef" :model="formState" :rules="rules">
      <a-form-item label="处理结果" name="description">
        <a-textarea :rows="4" v-model:value="formState.description" />
      </a-form-item>
    </a-form>
  </a-modal>
</template>

<script lang="ts">
import { PaginationType } from '@/components/BaseCrud/index.vue'
import encodeQuery from '@/utils/encodeQuery'
import { message, Modal } from 'ant-design-vue'
import { SelectTypes } from 'ant-design-vue/es/select'
import { defineComponent, h, onMounted, reactive, ref, toRaw, UnwrapRef } from 'vue'
import { getAlarmList, deleteAlarm, startAlarm, stopAlarm, getAlarmLogList, solveLog } from './service'
export type AlarmItem = {
  id: string;
  name: string;
  alarmRule?: Record<string, any>;
  createTime?: number;
  state?: {
    text: string;
    value: string;
  };
  target: string;
  targetId: string;
}
export default defineComponent({
  props: ['target', 'targetId'],
  setup (props) {
    const value = ref<string | undefined>(undefined)
    const dataSource = ref<AlarmItem[]>([])
    const searchParams = reactive<any>({
      pageSize: 10,
      terms: {
        productId: props.targetId,
        alarmId: undefined
      },
      sorts: {
        alarmTime: 'desc'
      }
    })
    const options = ref<SelectTypes['options']>([])
    const activeKey = ref<'1' | '2'>('1')
    const formRef = ref()
    const solveId = ref<string>('')
    const dataLogSource = ref<any>({
      data: [],
      pageSize: 10,
      total: 0
    })
    const visible = ref<boolean>(false)
    const formState: UnwrapRef<{description: string}> = reactive({
      description: ''
    })
    const columns = [
      {
        title: '名称',
        dataIndex: 'name',
        key: 'name',
        align: 'center'
      },
      {
        title: '创建时间',
        dataIndex: 'createTime',
        key: 'createTime',
        slots: { customRender: 'createTime' },
        align: 'center'
      },
      {
        title: '状态',
        dataIndex: 'state',
        key: 'state',
        slots: { customRender: 'state' },
        align: 'center'
      },
      {
        title: '操作',
        dataIndex: 'operation',
        key: 'operation',
        align: 'center',
        slots: { customRender: 'operation' }
      }
    ]
    const columnsLog = [
      {
        title: '设备ID',
        dataIndex: 'deviceId',
        key: 'deviceId',
        align: 'center'
      },
      {
        title: '设备名称',
        dataIndex: 'deviceName',
        key: 'deviceName',
        align: 'center'
      },
      {
        title: '告警名称',
        dataIndex: 'alarmName',
        key: 'alarmName',
        align: 'center'
      },
      {
        title: '创建时间',
        dataIndex: 'alarmTime',
        key: 'alarmTime',
        slots: { customRender: 'alarmTime' },
        align: 'center'
      },
      {
        title: '状态',
        dataIndex: 'state',
        key: 'state',
        slots: { customRender: 'state' },
        align: 'center'
      },
      {
        title: '操作',
        dataIndex: 'operation',
        key: 'operation',
        align: 'center',
        slots: { customRender: 'operation' }
      }
    ]
    const handleSearch = () => {
      getAlarmList(props.targetId, props.target).then(resp => {
        if (resp.data.status === 200) {
          dataSource.value = resp.data.result
          const list = resp.data.result.map((item: AlarmItem) => {
            return { label: item.name, value: item.id }
          })
          options.value = [...list]
        }
      })
    }
    const handleLogSearch = (value: string | undefined, pageIndex: number) => {
      searchParams.terms = {
        productId: props.targetId,
        alarmId: value
      }
      searchParams.pageIndex = pageIndex
      getAlarmLogList(encodeQuery(searchParams)).then(resp => {
        if (resp.data.status === 200) {
          dataLogSource.value = resp.data.result
        }
      })
    }

    onMounted(() => {
      handleSearch()
      handleLogSearch(undefined, 1)
    })

    const deleteAlarmBtn = (id: string) => {
      deleteAlarm(id).then(resp => {
        if (resp.data.status === 200) {
          message.success('删除成功！')
          handleSearch()
        }
      })
    }

    const startAlarmBtn = (id: string) => {
      startAlarm(id).then(resp => {
        if (resp.data.status === 200) {
          message.success('操作成功！')
          handleSearch()
        }
      })
    }

    const stopAlarmBtn = (id: string) => {
      stopAlarm(id).then(resp => {
        if (resp.data.status === 200) {
          message.success('操作成功！')
          handleSearch()
        }
      })
    }

    const handleChange = () => {
      handleLogSearch(value.value, 1)
    }

    const filterOption = (input: string, option: any) => {
      return option.value.toLowerCase().indexOf(input.toLowerCase()) >= 0
    }

    const handleTableChange = (page: PaginationType) => {
      handleLogSearch(value.value, page?.current - 1)
    }

    const getAlarmLog = (data: AlarmItem) => {
      value.value = data.id
      activeKey.value = '2'
      handleLogSearch(data.id, 1)
    }

    const activeChange = () => {
      value.value = undefined
      handleLogSearch(value.value, 1)
    }

    const info = (record: any) => {
      let content: string
      try {
        content = JSON.stringify(record.alarmData, null, 2)
      } catch (error) {
        content = record.alarmData
      }
      Modal.info({
        width: '40VW',
        title: () => '告警数据',
        content: () => h('div', {}, [
          h('pre', content),
          h('h4', '处理结果：'),
          h('pre', record.state !== 'newer' ? record.description : '未处理')
        ]),
        okText: '确定'
      })
    }

    const rules = {
      description: [
        { required: true, message: '请输入', trigger: 'blur' }
      ]
    }
    const solveAlarmLog = (id: string) => {
      visible.value = true
      solveId.value = id
    }
    const handleOk = () => {
      formRef.value.validate().then(() => {
        solveLog(solveId.value, toRaw(formState).description).then(resp => {
          if (resp.data.status === 200) {
            message.success('操作成功')
            handleLogSearch(value.value, searchParams.pageIndex)
          }
          visible.value = false
        })
      })
    }
    return {
      dataSource,
      columns,
      deleteAlarmBtn,
      startAlarmBtn,
      stopAlarmBtn,
      columnsLog,
      dataLogSource,
      filterOption,
      handleChange,
      options,
      value,
      handleTableChange,
      getAlarmLog,
      activeKey,
      activeChange,
      info,
      visible,
      handleOk,
      formState,
      rules,
      formRef,
      solveAlarmLog
    }
  }
})
</script>

// src/pages/device/alarm/index.tsx
import React, { Fragment, useEffect, useState } from 'react';
import {
  Badge,
  Button,
  Card,
  Divider,
  Input,
  message,
  Modal,
  Popconfirm,
  Select,
  Spin,
  Table,
  Tabs,
  Tag,
} from 'antd';
import apis from '@/services';
import { ColumnProps, SorterResult } from 'antd/es/table';
import { alarm, AlarmLog } from '@/pages/device/alarm/data';
import moment from 'moment';
import Save from '@/pages/device/alarm/save';
import Form from 'antd/es/form';
import { FormComponentProps } from 'antd/lib/form';
import { PaginationConfig } from 'antd/lib/table';
import encodeQueryParam from '@/utils/encodeParam';
import styles from '@/utils/table.less';

interface Props extends FormComponentProps {
  target: string;
  targetId?: string;
  metaData?: string;
  name?: string;
  productId?: string;
  productName?: string;
}

interface State {
  data: any[];
  saveAlarmData: Partial<alarm>;
  searchParam: any;
  alarmLogData: any;
  alarmDataList: any[];
}

const Alarm: React.FC<Props> = props => {
  const {
    form: { getFieldDecorator },
    form,
  } = props;

  const initState: State = {
    data: [],
    saveAlarmData: {},
    searchParam: {
      pageSize: 10,
      sorts: {
        order: 'descend',
        field: 'alarmTime',
      },
    },
    alarmLogData: {},
    alarmDataList: [],
  };

  const [data, setData] = useState(initState.data);
  const [spinning, setSpinning] = useState(true);
  const [saveVisible, setSaveVisible] = useState(false);
  const [solveVisible, setSolveVisible] = useState(false);
  const [saveAlarmData, setSaveAlarmData] = useState(initState.saveAlarmData);
  const [alarmActiveKey, setAlarmActiveKey] = useState('');
  const [alarmLogId, setAlarmLogId] = useState<any>(null);
  const [solveAlarmLogId, setSolveAlarmLogId] = useState();
  const [searchParam, setSearchParam] = useState(initState.searchParam);
  const [alarmLogData, setAlarmLogData] = useState(initState.alarmLogData);
  const [alarmDataList, setAlarmDataList] = useState(initState.alarmDataList);

  const statusMap = new Map();
  statusMap.set('运行中', 'success');
  statusMap.set('已停止', 'error');

  const getProductAlarms = () => {
    alarmDataList.splice(0, alarmDataList.length);
    apis.deviceAlarm
      .getProductAlarms(props.target, props.targetId)
      .then((response: any) => {
        if (response.status === 200) {
          setData(response.result);
          response.result.map((item: any) => {
            alarmDataList.push(item);
          });
          setAlarmDataList([...alarmDataList]);
        }
        setSpinning(false);
      })
      .catch(() => {});

    if (props.target === 'device') {
      apis.deviceAlarm
        .getProductAlarms('product', props.productId)
        .then((response: any) => {
          if (response.status === 200) {
            response.result.map((item: any) => {
              alarmDataList.push(item);
            });
            setAlarmDataList([...alarmDataList]);
          }
        })
        .catch(() => {});
    }
  };

  useEffect(() => {
    setAlarmActiveKey('info');
    getProductAlarms();
  }, []);

  const submitData = (data: any) => {
    apis.deviceAlarm
      .saveProductAlarms(props.target, props.targetId, data)
      .then((response: any) => {
        if (response.status === 200) {
          message.success('保存成功');
          setSaveVisible(false);
          getProductAlarms();
        }
        setSpinning(false);
      })
      .catch(() => {});
  };

  const _start = (item: alarm) => {
    apis.deviceAlarm
      ._start(item.id)
      .then((response: any) => {
        if (response.status === 200) {
          message.success('启动成功');
          getProductAlarms();
        } else {
          setSpinning(false);
        }
      })
      .catch();
  };

  const _stop = (item: any) => {
    apis.deviceAlarm
      ._stop(item.id)
      .then((response: any) => {
        if (response.status === 200) {
          message.success('停止成功');
          getProductAlarms();
        } else {
          setSpinning(false);
        }
      })
      .catch();
  };

  const deleteAlarm = (id: string) => {
    apis.deviceAlarm
      .remove(id)
      .then((response: any) => {
        if (response.status === 200) {
          getProductAlarms();
        } else {
          setSpinning(false);
        }
      })
      .catch(() => {});
  };

  const columns: ColumnProps<alarm>[] = [
    {
      title: '告警名称',
      dataIndex: 'name',
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      render: (text: any) => (text ? moment(text).format('YYYY-MM-DD HH:mm:ss') : '/'),
    },
    {
      title: '运行状态',
      dataIndex: 'state',
      render: record =>
        record ? <Badge status={statusMap.get(record.text)} text={record.text} /> : '',
    },
    {
      title: '操作',
      width: '250px',
      align: 'center',
      render: (record: any) => (
        <Fragment>
          <a
            onClick={() => {
              setSaveAlarmData(record);
              setSaveVisible(true);
            }}
          >
            编辑
          </a>
          <Divider type="vertical" />
          <a
            onClick={() => {
              setAlarmLogId(record.id);
              setAlarmActiveKey('logList');
            }}
          >
            告警日志
          </a>
          <Divider type="vertical" />
          {record.state?.value === 'stopped' ? (
            <span>
              <Popconfirm
                title="确认启动此告警？"
                onConfirm={() => {
                  setSpinning(true);
                  _start(record);
                }}
              >
                <a>启动</a>
              </Popconfirm>
              <Divider type="vertical" />
              <Popconfirm
                title="确认删除此告警？"
                onConfirm={() => {
                  setSpinning(true);
                  deleteAlarm(record.id);
                }}
              >
                <a>删除</a>
              </Popconfirm>
            </span>
          ) : (
            <Popconfirm
              title="确认停止此告警？"
              onConfirm={() => {
                setSpinning(true);
                _stop(record);
              }}
            >
              <a>停止</a>
            </Popconfirm>
          )}
        </Fragment>
      ),
    },
  ];

  const alarmLogColumns: ColumnProps<AlarmLog>[] = [
    {
      title: '设备ID',
      dataIndex: 'deviceId',
    },
    {
      title: '设备名称',
      dataIndex: 'deviceName',
    },
    {
      title: '告警名称',
      dataIndex: 'alarmName',
    },
    {
      title: '告警时间',
      dataIndex: 'alarmTime',
      width: '300px',
      render: (text: any) => (text ? moment(text).format('YYYY-MM-DD HH:mm:ss') : '/'),
      sorter: true,
      defaultSortOrder: 'descend',
    },
    {
      title: '处理状态',
      dataIndex: 'state',
      align: 'center',
      width: '100px',
      render: text =>
        text === 'solve' ? <Tag color="#87d068">已处理</Tag> : <Tag color="#f50">未处理</Tag>,
    },
    {
      title: '操作',
      width: '120px',
      align: 'center',
      render: (record: any) => (
        <Fragment>
          <a
            onClick={() => {
              let content: string;
              try {
                content = JSON.stringify(record.alarmData, null, 2);
              } catch (error) {
                content = record.alarmData;
              }
              Modal.confirm({
                width: '40VW',
                title: '告警数据',
                content: (
                  <pre>
                    {content}
                    {record.state === 'solve' && (
                      <>
                        <br />
                        <br />
                        <span style={{ fontSize: 16 }}>处理结果：</span>
                        <br />
                        <p>{record.description}</p>
                      </>
                    )}
                  </pre>
                ),
                okText: '确定',
                cancelText: '关闭',
              });
            }}
          >
            详情
          </a>
          <Divider type="vertical" />
          {record.state !== 'solve' && (
            <a
              onClick={() => {
                setSolveAlarmLogId(record.id);
                setSolveVisible(true);
              }}
            >
              处理
            </a>
          )}
        </Fragment>
      ),
    },
  ];

  const alarmSolve = () => {
    form.validateFields((err, fileValue) => {
      if (err) return;

      apis.deviceAlarm
        .alarmLogSolve(solveAlarmLogId || '', fileValue.description)
        .then((response: any) => {
          if (response.status === 200) {
            message.success('保存成功');
            setSolveAlarmLogId(undefined);
            setSolveVisible(false);
            handleSearch(searchParam);
          }
        })
        .catch(() => {});
    });
  };

  const handleSearch = (params?: any) => {
    setSearchParam(params);
    apis.deviceAlarm
      .findAlarmLog(encodeQueryParam(params))
      .then((response: any) => {
        if (response.status === 200) {
          setAlarmLogData(response.result);
        }
      })
      .catch(() => {});
  };

  const onAlarmProduct = (value: string) => {
    let { terms } = searchParam;
    if (terms) {
      terms.alarmId = value;
    } else {
      terms = {
        alarmId: value,
      };
    }
    handleSearch({
      pageIndex: searchParam.pageIndex,
      pageSize: searchParam.pageSize,
      terms,
      sorts: searchParam.sorter || {
        order: 'descend',
        field: 'alarmTime',
      },
    });
  };

  useEffect(() => {
    if (alarmActiveKey === 'logList') {
      if (props.target === 'device') {
        searchParam.terms = {
          deviceId: props.targetId,
        };
        if (alarmLogId != '' && alarmLogId != null && alarmLogId) {
          searchParam.terms.alarmId = alarmLogId;
        }
      } else {
        searchParam.terms = {
          productId: props.targetId,
        };
        if (alarmLogId != '' && alarmLogId != null && alarmLogId) {
          searchParam.terms.alarmId = alarmLogId;
        }
      }
      handleSearch(searchParam);
    }
  }, [alarmActiveKey]);

  const onTableChange = (
    pagination: PaginationConfig,
    filters: any,
    sorter: SorterResult<AlarmLog>,
  ) => {
    handleSearch({
      pageIndex: Number(pagination.current) - 1,
      pageSize: pagination.pageSize,
      terms: searchParam.terms,
      sorts: sorter,
    });
  };

  return (
    <Spin tip="加载中..." spinning={spinning}>
      <Card>
        <Tabs
          activeKey={alarmActiveKey}
          onTabClick={(key: any) => {
            setAlarmLogId(undefined);
            setAlarmActiveKey(key);
          }}
        >
          <Tabs.TabPane tab="告警设置" key="info">
            <Card
              title={
                <Button
                  icon="plus"
                  type="primary"
                  onClick={() => {
                    setSaveAlarmData({});
                    setSaveVisible(true);
                  }}
                >
                  新增告警
                </Button>
              }
              bordered={false}
            >
              <Table rowKey="id" columns={columns} dataSource={data} pagination={false} />
            </Card>
          </Tabs.TabPane>
          <Tabs.TabPane tab="告警记录" key="logList">
            <div>
              <Select
                placeholder="选择告警设置"
                allowClear
                style={{ width: 300 }}
                value={alarmLogId}
                onChange={(value: string) => {
                  onAlarmProduct(value);
                  setAlarmLogId(value);
                }}
              >
                {alarmDataList.length > 0 &&
                  alarmDataList.map(item => (
                    <Select.Option key={item.id}>{item.name}</Select.Option>
                  ))}
              </Select>
            </div>
            <div className={styles.StandardTable} style={{ marginTop: 10 }}>
              <Table
                dataSource={alarmLogData.data}
                columns={alarmLogColumns}
                rowKey="id"
                onChange={onTableChange}
                pagination={{
                  current: alarmLogData.pageIndex + 1,
                  total: alarmLogData.total,
                  pageSize: alarmLogData.pageSize,
                  showQuickJumper: true,
                  showSizeChanger: true,
                  pageSizeOptions: ['10', '20', '50', '100'],
                  showTotal: (total: number) =>
                    `共 ${total} 条记录 第  ${alarmLogData.pageIndex + 1}/${Math.ceil(
                      alarmLogData.total / alarmLogData.pageSize,
                    )}页`,
                }}
              />
            </div>
          </Tabs.TabPane>
        </Tabs>
      </Card>

      {saveVisible && (
        <Save
          close={() => {
            setSaveAlarmData({});
            setSaveVisible(false);
            getProductAlarms();
          }}
          save={(data: any) => {
            setSpinning(true);
            submitData(data);
          }}
          data={saveAlarmData}
          targetId={props.targetId}
          target={props.target}
          metaData={props.metaData}
          name={props.name}
          productName={props.productName}
          productId={props.productId}
        />
      )}

      {solveVisible && (
        <Modal
          title="告警处理结果"
          visible
          okText="确定"
          cancelText="取消"
          width="700px"
          onOk={() => {
            alarmSolve();
          }}
          onCancel={() => {
            setSolveVisible(false);
            setSolveAlarmLogId(undefined);
          }}
        >
          <Form labelCol={{ span: 3 }} wrapperCol={{ span: 21 }} key="solve_form">
            <Form.Item key="description" label="处理结果">
              {getFieldDecorator('description', {
                rules: [
                  { required: true, message: '请输入处理结果' },
                  { max: 2000, message: '处理结果不超过2000个字符' },
                ],
              })(<Input.TextArea rows={8} placeholder="请输入处理结果" />)}
            </Form.Item>
          </Form>
        </Modal>
      )}
    </Spin>
  );
};
export default Form.create<Props>()(Alarm);
