// src/pages/link/Certificate/index.tsx
import { PageContainer } from '@ant-design/pro-layout';
import BaseService from '@/utils/BaseService';
import type { CertificateItem } from '@/pages/link/Certificate/typings';
import { useRef } from 'react';
import type { ActionType, ProColumns } from '@jetlinks/pro-table';
import { message, Popconfirm, Tooltip } from 'antd';
import { EditOutlined, MinusOutlined } from '@ant-design/icons';
import BaseCrud from '@/components/BaseCrud';
import { useIntl } from '@@/plugin-locale/localeExports';
import type { ISchema } from '@formily/json-schema';
import { CurdModel } from '@/components/BaseCrud/model';

export const service = new BaseService<CertificateItem>('network/certificate');
const Certificate = () => {
  const intl = useIntl();
  const actionRef = useRef<ActionType>();

  const columns: ProColumns<CertificateItem>[] = [
    {
      dataIndex: 'index',
      valueType: 'indexBorder',
      width: 48,
    },
    {
      dataIndex: 'name',
      title: intl.formatMessage({
        id: 'pages.table.name',
        defaultMessage: '名称',
      }),
    },
    {
      dataIndex: 'instance',
      title: intl.formatMessage({
        id: 'pages.link.type',
        defaultMessage: '类型',
      }),
    },
    {
      dataIndex: 'description',
      title: intl.formatMessage({
        id: 'pages.table.describe',
        defaultMessage: '描述',
      }),
    },
    {
      title: intl.formatMessage({
        id: 'pages.data.option',
        defaultMessage: '操作',
      }),
      valueType: 'option',
      align: 'center',
      width: 200,
      render: (text, record) => [
        <a
          key="edit"
          onClick={() => {
            CurdModel.update(record);
            CurdModel.model = 'edit';
          }}
        >
          <Tooltip
            title={intl.formatMessage({
              id: 'pages.data.option.edit',
              defaultMessage: '编辑',
            })}
          >
            <EditOutlined />
          </Tooltip>
        </a>,
        <a key="delete">
          <Popconfirm
            title={intl.formatMessage({
              id: 'pages.data.option.remove.tips',
              defaultMessage: '确认删除？',
            })}
            onConfirm={async () => {
              await service.remove(record.id);
              message.success(
                intl.formatMessage({
                  id: 'pages.data.option.success',
                  defaultMessage: '操作成功!',
                }),
              );
              actionRef.current?.reload();
            }}
          >
            <Tooltip
              title={intl.formatMessage({
                id: 'pages.data.option.remove',
                defaultMessage: '删除',
              })}
            >
              <MinusOutlined />
            </Tooltip>
          </Popconfirm>
        </a>,
      ],
    },
  ];

  const schema: ISchema = {
    type: 'object',
    properties: {
      name: {
        title: '名称',
        'x-component': 'Input',
        'x-decorator': 'FormItem',
      },
      instance: {
        title: '类型',
        'x-component': 'Select',
        'x-decorator': 'FormItem',
        default: 'PEM',
        enum: [
          { label: 'PFX', value: 'PFX' },
          { label: 'JKS', value: 'JKS' },
          { label: 'PEM', value: 'PEM' },
        ],
      },
      configs: {
        type: 'object',
        properties: {
          '{url:keystoreBase64}': {
            title: '密钥库',
            'x-component': 'FUpload',
            'x-decorator': 'FormItem',
            'x-component-props': {
              type: 'file',
            },
          },
          keystorePwd: {
            title: '密钥库密码',
            'x-component': 'Password',
            'x-decorator': 'FormItem',
            'x-visible': false,
            'x-component-props': {
              style: {
                width: '100%',
              },
            },
            'x-reactions': {
              dependencies: ['..instance'],
              fulfill: {
                state: {
                  visible: '{{["JKS","PFX"].includes($deps[0])}}',
                },
              },
            },
          },
          '{url:trustKeyStoreBase64}': {
            title: '信任库',
            'x-component': 'FUpload',
            'x-decorator': 'FormItem',
            'x-component-props': {
              style: {
                width: '100px',
              },
              type: 'file',
            },
          },
          trustKeyStorePwd: {
            title: '信任库密码',
            'x-visible': false,
            'x-decorator': 'FormItem',
            'x-component': 'Password',
            'x-reactions': {
              dependencies: ['..instance'],
              fulfill: {
                state: {
                  visible: '{{["JKS","PFX"].includes($deps[0])}}',
                },
              },
            },
          },
        },
      },
      description: {
        title: '说明',
        'x-component': 'Input.TextArea',
        'x-decorator': 'FormItem',
      },
    },
  };

  return (
    <PageContainer>
      <BaseCrud
        columns={columns}
        service={service}
        title={intl.formatMessage({
          id: 'pages.link.certificate',
          defaultMessage: '证书管理',
        })}
        schema={schema}
        actionRef={actionRef}
      />
    </PageContainer>
  );
};
export default Certificate;

// src/views/pages/links/certificate/index.vue
<template>
  <page-container title="证书管理">
    <BaseCrud @event-change="eventChange" :form-data="formData" @modal-change="modalChange" @modal-visible="modalVisible" :model="model" :columns="columns" title="证书列表" :formPar="FormPar" :service="service" :default-params="defaultParams">
      <template #extra>
        <a-space>
          <a-button @click="addBtn" type="primary">新增</a-button>
        </a-space>
      </template>
      <template #status="slotProps">
        <template v-if="slotProps.value === 1">
          <a-tag color="#108ee9">正常</a-tag>
        </template>
        <template v-else>
          <a-tag color="#f50">禁用</a-tag>
        </template>
      </template>
      <template #action="{ record }">
        <a-space>
          <a @click="editBtn(record)">编辑</a>
          <a-popconfirm
            title="确认删除?"
            ok-text="确认"
            cancel-text="取消"
            @confirm="delBtn(record.id)"
          >
            <a>删除</a>
          </a-popconfirm>
        </a-space>
      </template>
    </BaseCrud>
  </page-container>
</template>

<script lang="ts">
import { defineComponent, reactive, ref } from 'vue'
import BaseCrud from '@/components/BaseCrud/index.vue'
import { FormProps } from '@/components/BaseForm/typing.d.ts'
import BaseService from '@/utils/base-service'
import { message } from 'ant-design-vue'
export interface UserItem {
  id?: string;
  name: string;
  status?: number;
  username: string;
  createTime?: number;
  email?: string;
  telephone?: string;
  avatar?: string;
  description?: string;
  password?: string;
  confirmPassword?: string;
}

export default defineComponent({
  components: {
    BaseCrud
  },
  setup () {
    const service = new BaseService<UserItem>('network/certificate')
    const columns = [
      {
        title: '名称',
        dataIndex: 'name',
        key: 'name',
        search: true,
        searchParams: {
          transform: (value: string) => ({ name$LIKE: value })
        }
      },
      {
        title: '类型',
        dataIndex: 'instance',
        key: 'instance',
        searchParams: {
          transform: (array: string[]) => ({ instance$IN: array.join(',') })
        },
        search: {
          mode: 'multiple',
          type: 'select',
          enum: [
            {
              key: 'PFX',
              label: 'PFX',
              value: 'PFX'
            },
            {
              key: 'JKS',
              label: 'JKS',
              value: 'JKS'
            },
            {
              key: 'PEM',
              label: 'PEM',
              value: 'PEM'
            }
          ]
        }
      },
      {
        title: '描述',
        dataIndex: 'description',
        key: 'description'
      },
      {
        title: '操作',
        dataIndex: 'action',
        key: 'action',
        slots: true
      }
    ]
    const FormPar = reactive<FormProps>({
      layout: 'vertical',
      formItems: [
        {
          name: 'name',
          rules: {
            trigger: 'blur',
            message: '请输入',
            required: true
          },
          label: '名称',
          formItemOptions: {
            type: 'input'
          }
        },
        {
          formItemOptions: {
            type: 'select',
            placeholder: '请选择',
            enum: [
              {
                label: 'PFX',
                value: 'PFX'
              },
              {
                label: 'JKS',
                value: 'JKS'
              },
              {
                label: 'PEM',
                value: 'PEM'
              }
            ]
          },
          rules: {
            required: true,
            message: '请输入'
          },
          name: 'instance',
          label: '类型'
        },
        {
          formItemOptions: {
            type: 'input'
          },
          name: 'configs.keystoreBase64',
          label: '密钥库'
        },
        {
          formItemOptions: {
            type: 'input'
          },
          name: 'configs.keystorePwd',
          label: '密钥库密码',
          visible: false
        },
        {
          formItemOptions: {
            type: 'input'
          },
          name: 'configs.trustKeyStoreBase64',
          label: '信任库',
          rules: {
            required: true,
            message: '请输入',
            trigger: 'blur'
          }
        },
        {
          formItemOptions: {
            type: 'input'
          },
          name: 'configs.trustKeyStorePwd',
          label: '信任库密码',
          visible: false
        },
        {
          formItemOptions: {
            type: 'textarea'
          },
          name: 'description',
          label: '描述',
          rules: {
            required: true,
            message: '请输入',
            trigger: 'blur'
          }
        }
      ]
    })
    const model = ref<'edit' | 'preview' | 'add' | 'refresh'>('preview')
    const formData = reactive({
      name: '',
      instance: '',
      configs: {
        keystorePwd: '',
        keystoreBase64: '',
        trustKeyStoreBase64: '',
        trustKeyStorePwd: ''
      },
      description: '',
      id: undefined
    })
    const defaultParams = {
      pageIndex: 0,
      pageSize: 10
    }
    const modalVisible = (value: 'edit' | 'preview' | 'add' | 'refresh') => {
      model.value = value
    }
    const visible = ref<boolean>(false)
    const current = ref()
    const inspection = (data: any) => {
      if (data.name === 'instance') {
        if (data.value === 'PEM') {
          FormPar.formItems[3].visible = false
          FormPar.formItems[5].visible = false
        } else {
          FormPar.formItems[3].visible = true
          FormPar.formItems[5].visible = true
        }
      }
    }
    const modalChange = (param: any) => {
      model.value = 'preview'
      service.update(param).then(res => {
        if (res.data.status === 200) {
          model.value = 'refresh'
        }
      })
    }
    const addBtn = () => {
      formData.id = undefined
      formData.instance = 'PEM'
      formData.name = ''
      formData.configs.keystoreBase64 = ''
      formData.configs.keystorePwd = ''
      formData.configs.trustKeyStoreBase64 = ''
      formData.configs.trustKeyStorePwd = ''
      formData.description = ''
      inspection({ value: 'PEM', name: 'instance' })
      model.value = 'add'
    }
    const editBtn = (data: any) => {
      formData.id = data.id
      formData.instance = data.instance
      formData.name = data.name
      formData.configs.keystorePwd = data.configs.keystorePwd
      formData.configs.keystoreBase64 = data.configs.keystoreBase64
      formData.configs.trustKeyStoreBase64 = data.configs.trustKeyStoreBase64
      formData.configs.trustKeyStorePwd = data.configs.trustKeyStorePwd
      formData.description = data.description
      inspection({ value: data.instance, name: 'instance' })
      model.value = 'edit'
    }
    const delBtn = (id: string) => {
      service.remove(id).then(res => {
        if (res.data.status === 200) {
          model.value = 'refresh'
        }
      })
    }
    const eventChange = (data: any) => {
      inspection(data)
    }
    return {
      columns,
      FormPar,
      service,
      defaultParams,
      model,
      formData,
      addBtn,
      editBtn,
      delBtn,
      modalVisible,
      modalChange,
      visible,
      current,
      eventChange
    }
  }
})
</script>
