// src/views/pages/device/product/detail/configuration/index.vue
<template>
  <a-drawer title="编辑配置" v-model:visible="modalVisible" @close="closeBtn" :width="450">
    <a-form :model="form" :label-col="labelCol" :wrapper-col="wrapperCol">
      <a-row :gutter="24">
        <template v-for="item in configForm" :key="item.name">
          <a-col :span="24">
            <h4>{{item.name}}</h4>
            <a-col v-for="i in item.properties" :key="i.name">
              <a-form-item :name="i.property">
                <template #label>{{i.name}}<a-tooltip v-if="i.description" :title="i.description"><QuestionCircleOutlined /></a-tooltip></template>
                <template v-if="i.type.id !== 'enum'">
                  <template v-if="i.type && i.type.type === 'password'">
                    <a-input-password v-model:value="form[i.property]" />
                  </template>
                  <template v-else>
                    <a-input v-model:value="form[i.property]" />
                  </template>
                </template>
                <template v-else>
                  <a-select v-model:value="form[i.property]">
                    <template v-for="j in i.type.elements" :key="j.value">
                      <a-select-option :value="j.value">{{j.text}}</a-select-option>
                    </template>
                  </a-select>
                </template>
              </a-form-item>
            </a-col>
          </a-col>
        </template>
      </a-row>
    </a-form>
    <div
      :style="{
        position: 'absolute',
        right: 0,
        bottom: 0,
        width: '100%',
        borderTop: '1px solid #e9e9e9',
        padding: '10px 16px',
        background: '#fff',
        textAlign: 'right',
        zIndex: 1,
      }"
    >
      <a-button style="margin-right: 8px" @click="closeBtn">取消</a-button>
      <a-dropdown>
      <template #overlay>
        <a-menu>
          <a-menu-item key="1" @click="okBtn(true)">仅保存</a-menu-item>
          <a-menu-item key="2" @click="okBtn(false)">保存并生效</a-menu-item>
        </a-menu>
      </template>
      <a-button type="primary">保存</a-button>
    </a-dropdown>
    </div>
  </a-drawer>
</template>

<script lang="ts">
import { defineComponent, ref, watchEffect, reactive, toRaw } from 'vue'
export default defineComponent({
  name: 'Configuration',
  props: ['modelValue', 'data', 'configuration'],
  emits: ['update:modelValue', 'ok-btn'],
  setup (props, { emit }) {
    const modalVisible = ref<boolean>(props.modelValue)
    const form = reactive<any>({})
    const configForm = ref<any[]>([])
    watchEffect(() => {
      modalVisible.value = props.modelValue
      configForm.value = props.configuration
      if (props.configuration) {
        props.configuration.forEach((item: any) => {
          if (item.properties) {
            item.properties.forEach((i: any) => {
              form[i.property] = props.data.configuration && props.data.configuration[i.property] ? props.data.configuration[i.property] : undefined
            })
          }
        })
      }
    })
    const okBtn = (onlySave: boolean) => {
      modalVisible.value = false
      emit('update:modelValue', false)
      emit('ok-btn', { onlySave, configuration: { ...toRaw(form) } })
    }
    const closeBtn = () => {
      modalVisible.value = false
      emit('update:modelValue', false)
    }

    return {
      form,
      modalVisible,
      okBtn,
      closeBtn,
      configForm,
      labelCol: { span: 6 },
      wrapperCol: { span: 18 }
    }
  }
})
</script>

// src/pages/device/instance/editor/detail/configuration.tsx
import React, { useEffect, useState } from 'react';
import { FormComponentProps } from 'antd/lib/form';
import Form from 'antd/es/form';
import { Button, Card, Col, Drawer, Icon, Input, Modal, Row, Select, Tooltip } from 'antd';
import { DeviceInstance } from '@/pages/device/instance/data';
import config from 'config/config';

interface Props extends FormComponentProps {
  data?: Partial<DeviceInstance>;
  configuration?: any;
  close: Function;
  save: (data: Partial<DeviceInstance>) => void;
}

interface State {
  protocolSupports: any[];
  protocolTransports: any[];
  organizationList: any[];
  configForm: any[];
  configName: string;
}

const Configuration: React.FC<Props> = props => {
  const initState: State = {
    protocolSupports: [],
    protocolTransports: [],
    organizationList: [],
    configName: '',
    configForm: [],
  };

  const { getFieldDecorator } = props.form;
  // 配置名称
  // const [configName, setConfigName] = useState(initState.configName);
  // 配置表单
  const [configForm, setConfigForm] = useState(initState.configForm);

  const parseConfig = (configData: any[]) => {
    const config = configData.map(i => {
      const configName = i.name
      let properties = i.properties.map((item: any) => {
        const label = item.description ? (
          <span>
            <span style={{marginRight: '10px'}}>{item.name}</span>
            <Tooltip title={item.description}>
              <Icon type="question-circle-o" />
            </Tooltip>
          </span>) : item.name
        const key = `configuration.${item.property}`;
        const componentType = item.type.id;
        let component = null;
        const options = {
          initialValue: props.data?.configuration[item.property],
        };
        if (componentType !== 'enum') {
          component = componentType === 'password' ? <Input.Password /> : <Input type={'text'} />;
        } else {
          const o = item.type.elements;
          component = (
            <Select>
              {(o || []).map((e: any) => (
                <Select.Option key={e.value} value={e.value}>
                  {e.text}
                </Select.Option>
              ))}
            </Select>
          );
        }
        return {
          label,
          key,
          styles: {
            xl: { span: 8 },
            lg: { span: 8 },
            md: { span: 12 },
            sm: { span: 24 },
          },
          options,
          component,
        };
      })
      return {
        configName,
        properties
      }
    });
    setConfigForm(config);
  };

  useEffect(() => {
    // setConfigName(props.configuration.name);
    // parseConfig(props.configuration.properties)
    parseConfig(props.configuration)
  }, []);


  const saveData = () => {
    const { form } = props;
    form.validateFields((err, fileValue) => {
      if (err) return;
      props.save(fileValue);
    });
  };

  return (
    <Drawer
      // title='编辑配置'
      // visible
      // okText="确定"
      // cancelText="取消"
      // onOk={() => {
      //   saveData();
      // }}
      // onCancel={() => props.close()}
      title='编辑配置1'
      visible
      width={500}
      onClose={() => props.close()}
      closable
    >
      <Form labelCol={{ span: 8 }} wrapperCol={{ span: 16 }}>
        {/* {configName && (
          <Card title={configName} style={{ marginBottom: 20 }} bordered={false}>
            <Row gutter={16}>
              {configForm.map(item => (
                <Col key={item.key}>
                  <Form.Item label={item.label}>
                    {getFieldDecorator(item.key, item.options)(item.component)}
                  </Form.Item>
                </Col>
              ))}
            </Row>
          </Card>
        )} */}
        {configForm && (
          // <Card title="配置" style={{ marginBottom: 20 }} bordered={false}>
          <Row gutter={16}>
            {configForm.map((item, index) => (
              <Col key={index}>
                <h4>{item.configName}</h4>
                {item.properties.map((i: any) => (
                  <Col key={i.key}>
                    <Form.Item label={i.label}>
                      {getFieldDecorator(i.key, i.options)(i.component)}
                    </Form.Item>
                  </Col>
                ))}
              </Col>
            ))}
          </Row>
          // </Card>
        )}
      </Form>
      <div
        style={{
          position: 'absolute',
          right: 0,
          bottom: 0,
          width: '100%',
          borderTop: '1px solid #e9e9e9',
          padding: '10px 16px',
          background: '#fff',
          textAlign: 'right',
        }}
      >
        <Button
          onClick={() => {
            props.close();
          }}
          style={{ marginRight: 8 }}
        >
          关闭
                </Button>
        <Button
          onClick={() => {
            saveData();
          }}
          type="primary"
        >
          保存
                </Button>
      </div>
    </Drawer>
  );
};

export default Form.create<Props>()(Configuration);
