// src/views/pages/system/tenant/index.vue
<template>
  <page-container title="租户管理">
    <BaseCrud :form-data="{}" @modal-visible="modalVisible" :model="model" :columns="columns" title="租户列表" :service="service" :default-params="defaultParams">
      <template #extra>
        <a-space>
          <a-button @click="addBtn" type="primary">新增</a-button>
        </a-space>
      </template>
      <template #name="{ record }">
        <a-avatar shape="square" :size="32" :src="record.tenant.photo"></a-avatar>
        <span style="margin-left: 10px;">{{ record.tenant.name }}</span>
      </template>
      <template #state="{ record }">
        <template v-if="record.tenant.state.value === 'enabled'">
          <a-tag color="#108ee9">{{ record.tenant.state.text }}</a-tag>
        </template>
        <template v-else>
          <a-tag color="#f50">{{ record.tenant.state.text }}</a-tag>
        </template>
      </template>
      <template #createTime="{ record }">
        <span>{{ $moment(record.tenant.createTime).format('YYYY-MM-DD HH:mm:ss') }}</span>
      </template>
      <template #action="{ record }">
        <a-space>
          <a>查看</a>
          <template v-if="record.tenant.state.value === 'enabled'">
            <a-popconfirm
              title="确认禁用?"
              ok-text="确认"
              cancel-text="取消"
              @confirm="changeState(record, 'disabled')"
            >
              <a>禁用</a>
            </a-popconfirm>
          </template>
          <template v-else>
            <a-popconfirm
              title="确认启用?"
              ok-text="确认"
              cancel-text="取消"
              @confirm="changeState(record, 'enabled')"
            >
              <a>启用</a>
            </a-popconfirm>
          </template>
        </a-space>
      </template>
    </BaseCrud>
  </page-container>
  <a-modal :width="500" title="新增租户" v-model:visible="visible" cancelText="取消" okText="确认" @ok="okBtn" @cancel="cancelBtn">
    <a-form :model="form" :rules="rules" layout="vertical">
      <a-form-item label="头像" name="photo">
        <FormUpload v-model="form.photo" />
      </a-form-item>
      <a-form-item label="名称" name="name">
        <a-input v-model:value="form.name" placeholder="请输入" />
      </a-form-item>
      <a-form-item label="用户名" name="username">
        <a-input v-model:value="form.username" placeholder="请输入"
        />
      </a-form-item>
      <a-form-item label="新密码" name="password">
        <a-input type="password" v-model:value="form.password" placeholder="请输入" />
      </a-form-item>
      <a-form-item label="确认密码" name="confirmPassword">
        <a-input type="password" v-model:value="form.confirmPassword" placeholder="请输入" />
      </a-form-item>
      <a-form-item label="描述" name="description">
        <a-textarea
          v-model:value="form.description"
          :rows="4"
          placeholder="请输入"
        />
      </a-form-item>
    </a-form>
  </a-modal>
</template>

<script lang="ts">
import { defineComponent, reactive, ref } from 'vue'
import BaseCrud from '@/components/BaseCrud/index.vue'
import FormUpload from '@/components/FormUpload/index.vue'
import BaseService from '@/utils/base-service'
import { createTenant, updateTenant } from './service'
import { message } from 'ant-design-vue'
type State = {
  value: string;
  text: string;
}
export type TenantDetail = {
  id: string;
  name: string;
  type: string;
  state: State;
  members: number;
  photo: string;
  createTime: number;
  description: string;
}

export type TenantItem = {
  members: number;
  tenant: Partial<TenantDetail>;
}

export default defineComponent({
  components: {
    BaseCrud,
    FormUpload
  },
  setup () {
    const service = new BaseService<TenantItem>('tenant/detail')
    const columns = [
      {
        title: '名称',
        dataIndex: 'name',
        key: 'name',
        slots: true
      },
      {
        title: '状态',
        dataIndex: 'state',
        align: 'center',
        key: 'state',
        slots: true
      },
      {
        title: '成员数量',
        align: 'center',
        dataIndex: 'members',
        key: 'members'
      },
      {
        title: '创建时间',
        dataIndex: 'createTime',
        key: 'createTime',
        align: 'center',
        slots: true
      },
      {
        title: '操作',
        dataIndex: 'action',
        key: 'action',
        align: 'center',
        slots: true
      }
    ]
    const model = ref<'edit' | 'preview' | 'add' | 'refresh'>('preview')
    const defaultParams = {
      pageIndex: 0,
      pageSize: 10,
      sorts: {
        id: 'desc'
      }
    }
    const visible = ref<boolean>(false)
    const form = reactive({
      name: '',
      username: '',
      photo: '',
      description: '',
      confirmPassword: '',
      password: ''
    })
    const rules = {
      name: [{ required: true, message: '请输入' }],
      username: [{ required: true, message: '请输入' }],
      confirmPassword: [{ required: true, message: '请输入' }],
      password: [{ required: true, message: '请输入' }]
    }
    const modalVisible = (value: 'edit' | 'preview' | 'add' | 'refresh') => {
      model.value = value
    }
    const addBtn = () => {
      visible.value = true
    }
    const initValue = () => {
      form.name = ''
      form.username = ''
      form.photo = ''
      form.description = ''
      form.confirmPassword = ''
      form.password = ''
    }
    const cancelBtn = () => {
      initValue()
      visible.value = false
    }
    const okBtn = () => {
      model.value = 'preview'
      createTenant(form).then(resp => {
        if (resp.data.status === 200) {
          message.success('操作成功！')
          model.value = 'refresh'
        }
        cancelBtn()
      })
    }
    const changeState = (data: any, state: string) => {
      const params = data.tenant
      params.state = state
      model.value = 'preview'
      updateTenant(params).then(resp => {
        if (resp.data.status === 200) {
          message.success('操作成功！')
          model.value = 'refresh'
        }
      })
    }
    return {
      columns,
      service,
      defaultParams,
      model,
      addBtn,
      modalVisible,
      form,
      visible,
      okBtn,
      cancelBtn,
      rules,
      changeState
    }
  }
})
</script>

// src/pages/system/Tenant/index.tsx
import { PageContainer } from '@ant-design/pro-layout';
import type { ProColumns, ActionType } from '@jetlinks/pro-table';
import type { TenantDetail } from '@/pages/system/Tenant/typings';
import type { TenantItem } from '@/pages/system/Tenant/typings';
import BaseCrud from '@/components/BaseCrud';
import { useRef } from 'react';
import { Avatar, message, Popconfirm, Tooltip } from 'antd';
import Service from '@/pages/system/Tenant/service';
import {
  CloseCircleOutlined,
  EyeOutlined,
  KeyOutlined,
  PlayCircleOutlined,
} from '@ant-design/icons';
import { useIntl } from '@@/plugin-locale/localeExports';
import moment from 'moment';
import { Link } from 'umi';
import TenantModel from '@/pages/system/Tenant/model';
import type { ISchema } from '@formily/json-schema';

export const service = new Service('tenant');

const Tenant = () => {
  const intl = useIntl();
  const actionRef = useRef<ActionType>();
  const columns: ProColumns<TenantItem>[] = [
    {
      dataIndex: 'index',
      valueType: 'indexBorder',
      width: 48,
    },
    {
      dataIndex: 'tenant',
      title: intl.formatMessage({
        id: 'pages.system.tenant.avatar',
        defaultMessage: '头像',
      }),
      align: 'center',
      search: false,
      renderText: (text: TenantDetail) => <Avatar src={text.photo} />,
    },
    {
      dataIndex: 'tenant',
      title: intl.formatMessage({
        id: 'pages.table.name',
        defaultMessage: '名称',
      }),
      align: 'center',
      renderText: (text: TenantDetail) => text.name,
      search: {
        transform: (value) => ({ name$LIKE: value }),
      },
    },
    {
      dataIndex: 'members',
      title: intl.formatMessage({
        id: 'pages.system.tenant.members',
        defaultMessage: '成员数',
      }),
      align: 'center',
      search: false,
    },
    {
      dataIndex: 'tenant',
      title: intl.formatMessage({
        id: 'pages.searchTable.titleStatus',
        defaultMessage: '状态',
      }),
      align: 'center',
      renderText: (text: TenantDetail) => text.state.text,
      valueType: 'select',
      hideInForm: true,
      onFilter: true,
      search: false,
      valueEnum: [
        {
          text: intl.formatMessage({
            id: 'pages.searchTable.titleStatus.all',
            defaultMessage: '全部',
          }),
          status: 'Default',
        },
        {
          text: intl.formatMessage({
            id: 'pages.searchTable.titleStatus.normal',
            defaultMessage: '正常',
          }),
          status: '1',
        },
        {
          text: intl.formatMessage({
            id: 'pages.searchTable.titleStatus.disable',
            defaultMessage: '禁用',
          }),
          status: '0',
        },
      ],
    },
    {
      title: '创建时间',
      dataIndex: 'tenant',
      width: '200px',
      align: 'center',
      renderText: (record: TenantDetail) => moment(record.createTime).format('YYYY-MM-DD HH:mm:ss'),
      sorter: true,
      search: false,
      defaultSortOrder: 'descend',
    },
    {
      title: intl.formatMessage({
        id: 'pages.data.option',
        defaultMessage: '操作',
      }),
      valueType: 'option',
      align: 'center',
      width: 200,
      render: (text, record) => [
        <Link
          onClick={() => {
            TenantModel.current = record;
          }}
          to={`/system/tenant/detail/${record.tenant.id}`}
          key="link"
        >
          <Tooltip
            title={intl.formatMessage({
              id: 'pages.data.option.detail',
              defaultMessage: '查看',
            })}
            key={'detail'}
          >
            <EyeOutlined />
          </Tooltip>
        </Link>,

        <a onClick={() => console.log('授权')}>
          <Tooltip
            title={intl.formatMessage({
              id: 'pages.data.option.authorize',
              defaultMessage: '授权',
            })}
          >
            <KeyOutlined />
          </Tooltip>
        </a>,
        <a href={record.tenant.id} target="_blank" rel="noopener noreferrer" key="view">
          <Popconfirm
            title={intl.formatMessage({
              id: 'pages.data.option.disabled.tips',
              defaultMessage: '确认禁用？',
            })}
            onConfirm={async () => {
              await service.update({
                tenant: {
                  id: record.tenant.id,
                  state: record.tenant?.state.value ? 0 : 1,
                },
              });
              message.success(
                intl.formatMessage({
                  id: 'pages.data.option.success',
                  defaultMessage: '操作成功!',
                }),
              );
              actionRef.current?.reload();
            }}
          >
            <Tooltip
              title={intl.formatMessage({
                id: `pages.data.option.${record.tenant?.state.value ? 'disabled' : 'enabled'}`,
                defaultMessage: record.tenant?.state?.value ? '禁用' : '启用',
              })}
            >
              {record.tenant?.state.value ? <CloseCircleOutlined /> : <PlayCircleOutlined />}
            </Tooltip>
          </Popconfirm>
        </a>,
      ],
    },
  ];

  const schema: ISchema = {
    type: 'object',
    properties: {
      name: {
        type: 'string',
        title: '名称',
        required: true,
        'x-decorator': 'FormItem',
        'x-component': 'Input',
      },
      username: {
        type: 'string',
        title: '用户名',
        required: true,
        'x-decorator': 'FormItem',
        'x-component': 'Input',
      },
      password: {
        type: 'string',
        title: '密码',
        required: true,
        'x-decorator': 'FormItem',
        'x-component': 'Password',
        'x-component-props': {
          checkStrength: true,
        },
        'x-reactions': [
          {
            dependencies: ['.confirmPassword'],
            fulfill: {
              state: {
                selfErrors:
                  '{{$deps[0] && $self.value && $self.value !== $deps[0] ? "确认密码不匹配" : ""}}',
              },
            },
          },
        ],
      },
      confirmPassword: {
        type: 'string',
        title: '确认密码',
        required: true,
        'x-decorator': 'FormItem',
        'x-component': 'Password',
        'x-component-props': {
          checkStrength: true,
        },
        'x-reactions': [
          {
            dependencies: ['.password'],
            fulfill: {
              state: {
                selfErrors:
                  '{{$deps[0] && $self.value && $self.value !== $deps[0] ? "确认密码不匹配" : ""}}',
              },
            },
          },
        ],
      },
      description: {
        type: 'string',
        title: '备注',
        required: true,
        'x-decorator': 'FormItem',
        'x-component': 'Input.TextArea',
      },
    },
  };

  return (
    <PageContainer>
      <BaseCrud<TenantItem>
        request={(params = {}) => service.queryList(params)}
        columns={columns}
        service={service}
        title={intl.formatMessage({
          id: 'pages.system.tenant.list',
          defaultMessage: '租户列表',
        })}
        schema={schema}
        actionRef={actionRef}
      />
    </PageContainer>
  );
};
export default Tenant;
