// src/pages/system/OpenAPI/index.tsx
import { PageContainer } from '@ant-design/pro-layout';
import React, { useRef } from 'react';
import type { ProColumns, ActionType } from '@jetlinks/pro-table';
import type { OpenApiItem } from '@/pages/system/OpenAPI/typings';
import { useIntl } from '@@/plugin-locale/localeExports';
import { CurdModel } from '@/components/BaseCrud/model';
import { Drawer, message, Popconfirm, Tooltip } from 'antd';
import {
  CloseCircleOutlined,
  EditOutlined,
  KeyOutlined,
  PlayCircleOutlined,
} from '@ant-design/icons';
import BaseCrud from '@/components/BaseCrud';
import BaseService from '@/utils/BaseService';
import autzModel from '@/components/Authorization/autz';
import Authorization from '@/components/Authorization';
import { observer } from '@formily/react';
import type { ISchema } from '@formily/json-schema';
import _ from 'lodash';

const service = new BaseService<OpenApiItem>('open-api');
const OpenAPI: React.FC = observer(() => {
  const intl = useIntl();
  const actionRef = useRef<ActionType>();

  const columns: ProColumns<OpenApiItem>[] = [
    {
      dataIndex: 'index',
      valueType: 'indexBorder',
      width: 48,
    },
    {
      title: 'clientId',
      dataIndex: 'id',
      sorter: true,
      defaultSortOrder: 'ascend',
      width: 200,
    },
    {
      title: intl.formatMessage({
        id: 'pages.table.name',
        defaultMessage: '名称',
      }),
      dataIndex: 'clientName',
    },
    {
      title: intl.formatMessage({
        id: 'pages.system.openApi.username',
        defaultMessage: '用户名',
      }),
      dataIndex: 'username',
    },
    {
      title: intl.formatMessage({
        id: 'pages.searchTable.titleStatus',
        defaultMessage: '状态',
      }),
      dataIndex: 'status',
      filters: true,
      align: 'center',
      renderText: (text: any) => text.text,
      valueType: 'select',
      hideInForm: true,
      onFilter: true,
      valueEnum: [
        {
          text: intl.formatMessage({
            id: 'pages.searchTable.titleStatus.all',
            defaultMessage: '全部',
          }),
          status: 'Default',
        },
        {
          text: intl.formatMessage({
            id: 'pages.searchTable.titleStatus.normal',
            defaultMessage: '正常',
          }),
          status: '1',
        },
        {
          text: intl.formatMessage({
            id: 'pages.searchTable.titleStatus.disable',
            defaultMessage: '禁用',
          }),
          status: '0',
        },
      ],
    },
    {
      title: intl.formatMessage({
        id: 'pages.data.option',
        defaultMessage: '操作',
      }),
      valueType: 'option',
      align: 'center',
      width: 200,
      render: (text, record) => [
        <a
          key="editable"
          onClick={() => {
            const temp = _.omit(record, ['createTime', 'creatorId', 'status']);
            CurdModel.update(temp);
          }}
        >
          <Tooltip
            title={intl.formatMessage({
              id: 'pages.data.option.edit',
              defaultMessage: '编辑',
            })}
          >
            <EditOutlined />
          </Tooltip>
        </a>,
        <a
          key="auth"
          onClick={() => {
            autzModel.autzTarget.id = record.id;
            autzModel.autzTarget.name = record.clientName;
            autzModel.visible = true;
          }}
        >
          <Tooltip
            title={intl.formatMessage({
              id: 'pages.data.option.authorize',
              defaultMessage: '授权',
            })}
          >
            <KeyOutlined />
          </Tooltip>
        </a>,
        <a key="state">
          <Popconfirm
            title={intl.formatMessage({
              id: 'pages.data.option.disabled.tips',
              defaultMessage: '确认禁用？',
            })}
            onConfirm={async () => {
              await service.update({
                id: record.id,
                status: record.status ? 0 : 1,
              });
              message.success(
                intl.formatMessage({
                  id: 'pages.data.option.success',
                  defaultMessage: '操作成功!',
                }),
              );
              actionRef.current?.reload();
            }}
          >
            <Tooltip
              title={intl.formatMessage({
                id: `pages.data.option.${record.status ? 'disabled' : 'enabled'}`,
                defaultMessage: record.status ? '禁用' : '启用',
              })}
            >
              {record.status ? <CloseCircleOutlined /> : <PlayCircleOutlined />}
            </Tooltip>
          </Popconfirm>
        </a>,
      ],
    },
  ];

  const schema: ISchema = {
    type: 'object',
    properties: {
      layout: {
        type: 'void',
        'x-component': 'FormGrid',
        'x-component-props': {
          maxColumns: 2,
        },
        properties: {
          clientName: {
            title: intl.formatMessage({
              id: 'pages.table.name',
              defaultMessage: '名称',
            }),
            type: 'string',
            'x-decorator': 'FormItem',
            'x-component': 'Input',
            'x-decorator-props': {
              labelCol: 6,
              wrapperCol: 18,
            },
            name: 'clientName',
          },
          enableOAuth2: {
            type: 'boolean',
            title: 'OAuth2',
            'x-decorator': 'FormItem',
            'x-component': 'Switch',
            'x-decorator-props': {
              labelCol: 6,
              wrapperCol: 18,
            },
            name: 'enableOAuth2',
          },
          id: {
            title: 'clientId',
            type: 'string',
            'x-decorator': 'FormItem',
            'x-component': 'Input',
            'x-decorator-props': {
              labelCol: 6,
              wrapperCol: 18,
            },
            name: 'clientId',
          },
          secureKey: {
            title: 'secureKey',
            type: 'string',
            'x-decorator': 'FormItem',
            'x-component': 'Input',
            'x-decorator-props': {
              labelCol: 6,
              wrapperCol: 18,
            },
            name: 'secureKey',
          },
          username: {
            title: intl.formatMessage({
              id: 'pages.system.openApi.username',
              defaultMessage: '用户名',
            }),
            type: 'string',
            'x-decorator': 'FormItem',
            'x-component': 'Input',
            'x-decorator-props': {
              labelWrap: false,
              wrapperWrap: false,
              labelCol: 6,
              wrapperCol: 18,
            },
            name: 'username',
          },
          password: {
            title: intl.formatMessage({
              id: 'pages.system.openApi.password',
              defaultMessage: '密码',
            }),
            type: 'string',
            'x-decorator': 'FormItem',
            'x-component': 'Input',
            'x-decorator-props': {
              labelCol: 6,
              wrapperCol: 18,
            },
            name: 'password',
          },
          redirectUrl: {
            title: 'redirectUrl',
            type: 'string',
            'x-decorator': 'FormItem',
            'x-component': 'Input',
            'x-visible': false,
            'x-decorator-props': {
              fullness: false,
              gridSpan: 2,
              labelAlign: 'right',
              wrapperAlign: 'left',
              labelCol: 3,
              wrapperCol: 21,
            },
            name: 'redirectUrl',
            'x-reactions': {
              dependencies: [
                {
                  property: 'value',
                  source: '.enableOAuth2',
                  name: 'enableOAuth2',
                },
              ],
              fulfill: {
                state: {
                  visible: '{{$deps.enableOAuth2}}',
                },
              },
            },
          },
        },
      },
      ipWhiteList: {
        title: intl.formatMessage({
          id: 'pages.system.openApi.ipWhileList',
          defaultMessage: 'IP白名单',
        }),
        type: 'string',
        'x-decorator': 'FormItem',
        'x-component': 'Input.TextArea',
        'x-component-props': {},
        'x-decorator-props': {
          labelCol: 3,
          wrapperCol: 21,
        },
        name: 'ipWhiteList',
      },
      description: {
        title: intl.formatMessage({
          id: 'pages.table.describe',
          defaultMessage: '描述',
        }),
        type: 'string',
        'x-decorator': 'FormItem',
        'x-component': 'Input.TextArea',
        'x-component-props': {},
        'x-decorator-props': {
          labelCol: 3,
          wrapperCol: 21,
        },
        name: 'description',
      },
    },
  };

  return (
    <PageContainer>
      <BaseCrud<OpenApiItem>
        columns={columns}
        service={service}
        title={intl.formatMessage({
          id: 'pages.system.openApi',
          defaultMessage: '第三方平台',
        })}
        schema={schema}
        modelConfig={{ width: 900 }}
        actionRef={actionRef}
      />
      <Drawer
        title={intl.formatMessage({
          id: 'pages.data.option.authorize',
          defaultMessage: '授权',
        })}
        width="70vw"
        visible={autzModel.visible}
        onClose={() => {
          autzModel.visible = false;
        }}
      >
        <Authorization
          close={() => {
            autzModel.visible = false;
          }}
          target={autzModel.autzTarget}
        />
      </Drawer>
    </PageContainer>
  );
});

export default OpenAPI;

// src/views/pages/system/open-api/index.vue
<template>
  <page-container title="第三方平台">
    <BaseCrud :form-data="{}" @modal-visible="modalVisible" :model="model" :columns="columns" title="平台列表" :service="service" :default-params="defaultParams">
      <template #extra>
        <a-space>
          <a-button @click="addBtn" type="primary">新增</a-button>
        </a-space>
      </template>
      <template #status="slotProps">
        <template v-if="slotProps.value.value === 1">
          <a-tag color="#108ee9">{{ slotProps.value.text }}</a-tag>
        </template>
        <template v-else>
          <a-tag color="#f50">{{ slotProps.value.text }}</a-tag>
        </template>
      </template>
      <template #action="{ record }">
        <a-space>
          <a @click="editBtn(record)">编辑</a>
          <a @click="authorizeBtn(record)">赋权</a>
          <template v-if="record.status.value === 1">
            <a-popconfirm
              title="确认禁用?"
              ok-text="确认"
              cancel-text="取消"
              @confirm="delBtn(record.id)"
            >
              <a>禁用</a>
            </a-popconfirm>
          </template>
          <template v-else>
            <a-popconfirm
              title="确认启用?"
              ok-text="确认"
              cancel-text="取消"
              @confirm="enableOrDisable(record)"
            >
              <a>启用</a>
            </a-popconfirm>
            <a-popconfirm
              title="确认删除?"
              ok-text="确认"
              cancel-text="取消"
              @confirm="delBtn(record.id)"
            >
              <a>删除</a>
            </a-popconfirm>
          </template>
        </a-space>
      </template>
    </BaseCrud>
  </page-container>
  <a-modal title="新增" v-model:visible="visible" okText="确定" cancelText="取消" @ok="saveForm" @cancel="cancelForm">
    <a-form :model="form" :rules="rules" layout="vertical">
      <a-form-item label="名称" name="clientName">
        <a-input v-model:value="form.clientName" placeholder="请输入"/>
      </a-form-item>
      <a-form-item label="ID" name="clientId">
        <a-input :disabled="true" v-model:value="form.clientId" placeholder="请输入"/>
      </a-form-item>
      <a-form-item label="secureKey" name="secureKey">
        <a-input v-model:value="form.secureKey" placeholder="请输入"/>
      </a-form-item>
      <a-form-item label="username" name="username">
        <a-input v-model:value="form.username" placeholder="请输入"/>
      </a-form-item>
      <a-form-item label="password" name="password">
        <a-input type="password" v-model:value="form.password" placeholder="请输入"/>
      </a-form-item>
      <a-form-item label="开启OAuth2" name="enableOAuth2">
        <a-radio-group v-model:value="form.enableOAuth2" button-style="solid">
          <a-radio-button :value="true">开启</a-radio-button>
          <a-radio-button :value="false">关闭</a-radio-button>
        </a-radio-group>
      </a-form-item>
      <a-form-item v-if="form.enableOAuth2" label="redirectUrl" name="redirectUrl">
        <a-input v-model:value="form.redirectUrl" placeholder="请输入"/>
      </a-form-item>
      <a-form-item label="IP白名单" name="ipWhiteList">
        <a-textarea
          v-model:value="form.ipWhiteList"
          :rows="3"
          placeholder="请输入"
        />
      </a-form-item>
      <a-form-item label="描述" name="description">
        <a-textarea
          v-model:value="form.description"
          :rows="3"
          placeholder="请输入"
        />
      </a-form-item>
    </a-form>
  </a-modal>
  <Authorization v-model="authVisible" :data="current" />
</template>

<script lang="ts">
import Authorization from '@/components/Authorization/index.vue'
import { defineComponent, reactive, ref, watch } from 'vue'
import BaseCrud from '@/components/BaseCrud/index.vue'
import BaseService from '@/utils/base-service'
import { uid } from '@/utils/uid'
import { message } from 'ant-design-vue'
export type OpenApiItem = {
  id: string;
  username?: string;
  userId?: string;
  password: string;
  clientName: string;
  createTime: number;
  creatorId: string;
  description: string;
  ipWhiteList: string;
  secureKey: string;
  signature: string;
  enableOAuth2: boolean;
  redirectUrl: string;
  status: number;
};

export default defineComponent({
  components: {
    BaseCrud,
    Authorization
  },
  setup () {
    const service = new BaseService<OpenApiItem>('open-api')
    const columns = [
      {
        title: '标识',
        dataIndex: 'id',
        key: 'id',
        search: true,
        searchParams: {
          transform: (value: string) => ({ id$LIKE: value })
        }
      },
      {
        title: '名称',
        dataIndex: 'clientName',
        key: 'clientName',
        search: true,
        searchParams: {
          transform: (value: string) => ({ clientName$LIKE: value })
        }
      },
      {
        title: '用户名',
        dataIndex: 'username',
        key: 'username'
      },
      {
        title: '状态',
        slots: true,
        dataIndex: 'status',
        key: 'status'
      },
      {
        title: '操作',
        dataIndex: 'action',
        key: 'action',
        slots: true
      }
    ]
    const visible = ref<boolean>(false)
    const authVisible = ref<boolean>(false)
    const current = ref<any>()
    const form = reactive({
      id: '',
      clientName: '',
      clientId: uid(16),
      secureKey: uid(24),
      username: '',
      password: '',
      enableOAuth2: false,
      ipWhiteList: '',
      description: '',
      redirectUrl: ''
    })
    const rules = {
      clientId: [{ required: true, message: '请输入' }],
      clientName: [{ required: true, message: '请输入' }],
      secureKey: [{ required: true, message: '请输入' }],
      username: [{ required: true, message: '请输入' }]
    }
    const model = ref<'edit' | 'preview' | 'add' | 'refresh'>('preview')
    const defaultParams = {
      pageIndex: 0,
      pageSize: 10
    }
    const schema = {
      type: 'object',
      properties: {
        input: {
          type: 'string',
          title: '输入框',
          required: true,
          'x-decorator': 'FormItem',
          'x-component': 'Input'
        }
      }
    }
    const modalVisible = (value: 'edit' | 'preview' | 'add' | 'refresh') => {
      model.value = value
    }
    const addBtn = () => {
      form.id = ''
      form.clientName = ''
      form.clientId = uid(16)
      form.secureKey = uid(24)
      form.username = ''
      form.password = ''
      form.enableOAuth2 = false
      form.ipWhiteList = ''
      form.description = ''
      form.redirectUrl = ''
      visible.value = true
    }
    const editBtn = (data: OpenApiItem) => {
      Object.assign(form, data)
      visible.value = true
    }
    const delBtn = (id: string) => {
      model.value = 'preview'
      service.remove(id).then(res => {
        if (res.data.status === 200) {
          model.value = 'refresh'
        }
      })
    }
    watch(() => visible, (newValue) => {
      if (newValue) {
        form.clientId = uid(16)
        form.secureKey = uid(24)
      }
    })
    const cancelForm = () => {
      visible.value = false
    }
    const updateData = (data: any) => {
      model.value = 'preview'
      service.update(data).then(resp => {
        if (resp.data.status === 200) {
          message.success('操作成功')
          model.value = 'refresh'
        }
      })
    }
    const saveForm = () => {
      const data = {
        clientName: form.clientName,
        description: form.description,
        enableOAuth2: form.enableOAuth2,
        id: form.id,
        ipWhiteList: form.ipWhiteList,
        redirectUrl: form.redirectUrl,
        secureKey: form.secureKey,
        signature: 'MD5',
        username: form.username
      }
      updateData({ ...data })
      visible.value = false
    }
    const enableOrDisable = (record: any) => {
      updateData({
        id: record.id,
        status: record.status?.value === 1 ? 0 : 1
      })
    }
    const authorizeBtn = (data: OpenApiItem) => {
      authVisible.value = true
      current.value = {
        id: data.id,
        name: data.clientName,
        targetType: 'open-api'
      }
    }
    return {
      visible,
      columns,
      service,
      defaultParams,
      model,
      form,
      schema,
      addBtn,
      editBtn,
      delBtn,
      modalVisible,
      saveForm,
      cancelForm,
      authVisible,
      current,
      rules,
      enableOrDisable,
      authorizeBtn
    }
  }
})
</script>
