// src/views/pages/system/permission/save/data-view.vue
<template>
  <a-card title="关联权限">
    <template #extra>
      <slot name="extra">
        <a-button type="primary" @click="add">新增</a-button>
      </slot>
    </template>
    <a-table :pagination="false" :rowKey="getRowKey" :columns="columns" :data-source="dataSource" bordered>
      <template v-for="col in ['name', 'describe']" #[col]="{ text, record }" :key="col">
        <div>
          <a-input
            v-if="editableData[record.key]"
            v-model:value="editableData[record.key][col]"
            style="margin: -5px 0"
          />
          <template v-else>
            {{ text }}
          </template>
        </div>
      </template>
      <template #operation="{ record }">
        <div class="editable-row-operations">
          <a-space v-if="editableData[record.key]">
            <a @click="save(record.key)">保存</a>
            <a-popconfirm title="确认取消?" ok-text="确认" cancel-text="取消" @confirm="cancel(record.key)">
              <a>取消</a>
            </a-popconfirm>
          </a-space>
          <a-space v-else>
            <a @click="edit(record.key)">编辑</a>
            <a-popconfirm title="确认删除?" ok-text="确认" cancel-text="取消" @confirm="remove(record.key)">
              <a>删除</a>
            </a-popconfirm>
          </a-space>
        </div>
      </template>
    </a-table>
  </a-card>
</template>

<script lang="ts">
import { defineComponent, reactive, ref, UnwrapRef, watch } from 'vue'
import { uid } from '@/utils/uid'
import _ from 'lodash'
interface DataViewItem {
  key: string,
  describe: string,
  name: string
}
export default defineComponent({
  name: 'DataView',
  props: ['modelValue'],
  emits: ['update:modelValue'],
  setup (props, { emit }) {
    const columns = [
      {
        title: '字段',
        dataIndex: 'name',
        width: '33%',
        slots: { customRender: 'name' }
      },
      {
        title: '描述',
        dataIndex: 'describe',
        width: '33%',
        slots: { customRender: 'describe' }
      },
      {
        title: '操作',
        width: '34%',
        dataIndex: 'operation',
        slots: { customRender: 'operation' }
      }
    ]
    const dataSource = ref(props.modelValue)
    watch(props.modelValue, () => {
      dataSource.value = props.modelValue
    })
    const editableData: UnwrapRef<Record<string, DataViewItem>> = reactive({})
    const add = () => {
      const key = uid()
      const data = {
        key,
        describe: '',
        name: ''
      }
      dataSource.value.push(data)
      editableData[key] = data
    }
    const edit = (key: string) => {
      editableData[key] = _.cloneDeep(dataSource.value.filter((item: DataViewItem) => key === item.key)[0])
    }
    const save = (key: string) => {
      Object.assign(dataSource.value.filter((item: DataViewItem) => key === item.key)[0], editableData[key])
      delete editableData[key]
      emit('update:modelValue', dataSource.value)
    }
    const cancel = (key: string) => {
      delete editableData[key]
    }
    const remove = (key: string) => {
      _.remove(dataSource.value, (n: DataViewItem) => {
        return n.key === key
      })
      emit('update:modelValue', dataSource.value)
    }
    const getRowKey = () => {
      return `data-view${uid()}`
    }
    return {
      dataSource,
      columns,
      editingKey: '',
      editableData,
      edit,
      save,
      cancel,
      remove,
      add,
      getRowKey
    }
  }
})
</script>

// src/pages/system/permission/Save/data-view/index.tsx
import { Table, Input, Popconfirm, Form, Divider, message, Icon } from 'antd';
import React, { useState, Fragment, useContext } from 'react';
import { FormComponentProps } from 'antd/es/form';
import { DataViewItem } from '../../data';

const EditableContext = React.createContext({});

const EditableCell: React.FC = (props: any) => {

    const form: any = useContext(EditableContext);

    const getInput = () => {
        return <Input size="small" />;
    };

    const { getFieldDecorator } = form;
    const {
        editing,
        dataIndex,
        title,
        inputType,
        record,
        index,
        children,
        ...restProps
    } = props;


    return (
        <td {...restProps}>
            {editing ? (
                <Form.Item style={{ margin: 0 }}>
                    {getFieldDecorator(dataIndex, {
                        rules: [
                            {
                                required: true,
                                message: `请输入 ${title}!`,
                            },
                        ],
                        initialValue: record[dataIndex],
                    })(getInput())}
                </Form.Item>
            ) : (
                    children
                )}
        </td>
    );
}

interface EditableTableProps extends FormComponentProps {
    data: DataViewItem[];
    save: Function;
}

interface EditableTableState {
    data: DataViewItem[];
    editingKey: string;
}

const DataView: React.FC<EditableTableProps> = (props) => {

    const initState: EditableTableState = {
        data: props.data,
        editingKey: '',
    }
    const [editingKey, setEditingKey] = useState(initState.editingKey);
    const [data, setData] = useState(initState.data);
    const cancel = () => {
        setEditingKey('');
    };

    const isEditing = (record: DataViewItem) => record.key === editingKey;

    const components = {
        body: {
            cell: EditableCell,
        },
    };

    const columnsTemp: any[] = [
        {
            title: '字段',
            dataIndex: 'name',
            width: '40%',
            editable: true,
        },
        {
            title: '描述',
            dataIndex: 'describe',
            width: '40%',
            editable: true,
        },
        {
            title: (
                <span>
                    操作
                    <Divider type="vertical" />
                    <Icon type="plus" onClick={() => handleAdd()} />
                </span>),
            dataIndex: 'operation',
            render: (text: any, record: DataViewItem) => {

                const editable = isEditing(record);
                return editable ? (
                    <span>
                        {
                            <a
                                onClick={() => save(props.form, record.key)}
                                style={{ marginRight: 8 }}
                            >
                                保存
                                </a>
                        }
                        <Popconfirm title="确认取消？" onConfirm={() => cancel()}>
                            <a>取消</a>
                        </Popconfirm>
                    </span >
                ) : (
                        <Fragment>
                            <a type="link" onClick={() => edit(record.key)}>
                                编辑
                            </a>
                            <Divider type="vertical" />
                            <a type="link" onClick={() => remove(record.key)}>
                                删除
                            </a>
                        </Fragment>
                    );

            },
        },
    ];

    const columns = columnsTemp.map((col: any) => {
        if (!col.editable) {
            return col;
        }
        return {
            ...col,
            onCell: (record: any) => ({
                record,
                dataIndex: col.dataIndex,
                title: col.title,
                editing: isEditing(record),
            }),
        };
    });

    const save = (form: any, key: string) => {
        form.validateFields((error: any, row: any) => {
            if (error) {
                return;
            }
            const newData = [...data];
            const index = newData.findIndex(item => key === item.key);
            if (index > -1) {
                const item = newData[index];
                newData.splice(index, 1, {
                    ...item,
                    ...row,
                });
                setData(newData);
                setEditingKey('');
            } else {
                newData.push(row);
                setData(newData);
                setEditingKey('');
            }
            props.save(newData);
        });
    }

    const edit = (key: string) => {
        setEditingKey(key);
    }

    const remove = (key: string) => {
        const newData = data.filter(item => item.key !== key);
        setData(newData);
        props.save(newData);
    }

    const handleAdd = () => {
        const key = data.length + 1 + '';
        data.push({
            key: key,
            describe: '',
            name: '',
        });
        setData(data);
        setEditingKey(key);
    }

    return (
        <EditableContext.Provider value={props.form}>
            <Table
                size="small"
                rowKey="name"
                components={components}
                bordered
                dataSource={data}
                columns={columns}
                rowClassName={() => "editable-row"}
                pagination={false}
                onChange={() => message.success('保存成功！！')}
            />
        </EditableContext.Provider>
    );
}

export default Form.create<EditableTableProps>()(DataView);
