// src/components/Authorization/index.tsx
import { Button, Checkbox, Drawer, Form, Input, Select, Table, message, Divider } from 'antd';
import React, { Fragment, useState, useEffect } from 'react';
import apis from '@/services';
import { DimensionsItem, DimensionType } from '@/pages/system/dimensions/data';
import { groupBy, cloneDeep } from 'lodash';
import { FormComponentProps } from 'antd/es/form';
import styles from './index.less';
import DataAccess from './DataAccess';
import encodeQueryParam from '@/utils/encodeParam';

interface Props extends FormComponentProps {
  close: Function;
  target?: any;
  targetType?: string;
}

interface State {
  dataAccessVisible: boolean;
  permissionList: any[];
  checkPermission: any;
  permissionType: string;
  searchText: string;
  dimensionList: any[];
  targetAutz: any[];
  tempAccess: any[];
}
const Authorization: React.FC<Props> = props => {
  const initState: State = {
    dataAccessVisible: false,
    permissionList: [],
    checkPermission: {},
    permissionType: 'all',
    searchText: '',
    dimensionList: [],
    targetAutz: [],
    tempAccess: [],
  };
  const [permissionList, setPermissionList] = useState(initState.permissionList);
  const [dataAccessVisible, setDataAccessVisible] = useState(initState.dataAccessVisible);
  const [checkPermission, setCheckPermission] = useState(initState.checkPermission);
  const [permissionType, setPermissionType] = useState(initState.permissionType);
  const [searchText, setSearchText] = useState(initState.searchText);
  const [dimensionList, setDimensionList] = useState(initState.dimensionList);
  const [targetAutz, setTargetAutz] = useState(initState.targetAutz);
  const [tempAccess, setTempAccess] = useState(initState.tempAccess);

  const {
    form: { getFieldDecorator },
    // form,
  } = props;

  const getDimensions = () => {
    apis.dimensions.typeList().then(e => {
      if (e && e.status === 200) {
        apis.dimensions.treeList().then(d => {
          if (d.status === 200) {
            const tempList = d.result.map((dr: DimensionsItem) => {
              const type = e.result.find((t: DimensionType) => t.id === dr.typeId);
              if (type) {
                const typeName = type.name;
                return { typeName, ...dr };
              }
              return dr;
            });
            setDimensionList(tempList);
          }
        });
      }
    });
  };

  useEffect(() => {
    apis.permission
      .listNoPaging()
      .then(response => {
        if (response.status === 200) {
          const temp: any[] = response.result;
          const list = temp.filter(item => (item.actions || []).length > 0);
          setPermissionList(list);
        }
      })
      .catch(() => {});
    if (props.target.id) {
      apis.authorization
        .list(
          encodeQueryParam({
            paging: false,
            terms: {
              dimensionTarget: props.target.id,
            },
          }),
        )
        .then(response => {
          if (response.status === 200) {
            // const { result } = response;
            // const resultTemp = result.map((item: any) => ({ id: item.permisseion, ...item }))
            setTargetAutz(response.result);
          }
        })
        .catch(() => {});
    }

    // apis.authorization.autzDetail({ type: props.targetType, id: props.targetId }).then(response => {
    //   console.log(response, 'response');
    // })
    getDimensions();
  }, []);

  const saveDataAccess = (data: any) => {
    // 如果有，删除原数据
    const temp = tempAccess.filter(i => i.permissionId !== data.permissionId);
    // 保存数据
    setTempAccess([...temp, data]);
    // 字段权限
    // 先创建Map
    const tempMap = new Map();
    const key = new Set();
    // 遍历出所有操作
    const { fieldAccess } = data;

    // eslint-disable-next-line no-restricted-syntax
    for (const item of fieldAccess) {
      // eslint-disable-next-line no-restricted-syntax
      for (const action of item.action) {
        key.add(action);
      }
    }

    // 创建Map
    Array.from(key).forEach(i => tempMap.set(i, []));
    // 赋值

    // eslint-disable-next-line no-restricted-syntax
    for (const item of fieldAccess) {
      // eslint-disable-next-line no-restricted-syntax
      for (const action of item.action) {
        const tem = tempMap.get(action);
        tempMap.set(action, [...tem, item.name]);
      }
    }

    // 构造数据结构
    const tempFiledAccess = [...tempMap.keys()].map(action => ({
      action,
      type: 'DENY_FIELDS',
      describe: '不能操作的字段',
      config: {
        fields: tempMap.get(action),
      },
    }));

    // 数据权限
    const { dataAccess } = data;

    const tempDataMap = new Map();

    const dataKey = new Set();

    // eslint-disable-next-line no-restricted-syntax
    for (const item of dataAccess) {
      // eslint-disable-next-line no-restricted-syntax
      for (const type of item.action) {
        dataKey.add(type);
      }
    }
    //
    Array.from(dataKey).forEach(i => tempDataMap.set(i, []));
    // 赋值
    // eslint-disable-next-line no-restricted-syntax
    for (const item of dataAccess) {
      // eslint-disable-next-line no-restricted-syntax
      for (const action of item.action) {
        const temp1 = tempDataMap.get(action);
        tempDataMap.set(action, [...temp1, item.type]);
      }
    }

    // 构造数据结构
    const tempDataAccess = [...tempDataMap.keys()].map(action => ({
      action,
      type: 'DIMENSION_SCOPE',
      config: {
        scopeType: tempDataMap.get(action).join(','),
        children: true,
      },
    }));

    // 修改数据

    let item: any = {};
    const update = targetAutz.find(i => i.permission === data.permissionId);
    if (update) {
      item = update;
      item.dataAccesses = [...tempFiledAccess, ...tempDataAccess];
    } else {
      item = {
        permission: data.permissionId,
        dimensionType: props.targetType,
        dimensionTypeName: '用户',
        dimensionTarget: props.target.id,
        dimensionTargetName: props.target.name,
        state: 1,
        dataAccesses: [...tempFiledAccess, ...tempDataAccess],
        merge: 10,
      };
    }

    // 新增（查询出来的接口没有此权限）

    // 删除修改的数据。
    const tempAutz = targetAutz.filter(i => i.permission !== data.permissionId);
    // console.log(tempAutz, item, data, '更细的数据');
    setTargetAutz([...tempAutz, item]);
    message.success('保存成功');
    // autzSetting(data)
    // TODO 此处调用接口保存数据
  };

  const autzSetting = () => {
    // 注释原因：使用搜索过滤后，过滤前的数据无法获取。对应阿里云2324892缺陷
    // const { permissions } = form.getFieldsValue();
    // const tempAutz: any[] = [];
    // for (const key in permissions) {
    //   if (permissions.hasOwnProperty(key)) {
    //     const element = permissions[key];
    //     if (element) {
    //       const access = tempAccess.find(i => i.permissionId === key);
    //       tempAutz.push({ id: key, actions: element, ...access });
    //     }
    //   }
    // }
    // const resultTemp = targetAutz.map((item: any) => ({ id: item.permisseion, ...item }));
    const autzData = targetAutz.map(i => ({ id: i.permission, actions: i.actions }));
    apis.authorization
      .saveAutz({
        targetId: props.target.id,
        targetType: props.targetType,
        permissionList: autzData, // 修复2324892缺陷 将tempAutz换成了targetAutz
      })
      .then(response => {
        if (response.status === 200) {
          message.success('授权成功');
        }
      })
      .catch(() => {});
    // console.log({
    //   targetId: props.targetId,
    //   targetType: props.targetType,
    //   permissionList: tempAutz
    // }, 'auzt');
    // console.log(authorization, 'logs');
    // let tempAutz = {
    //   targetId: authorization.autz.dimensionTarget,
    //   targetType: 'user',
    //   permisionList: [

    //   ]
    // }
    // let tempAutz = {
    //   permission: authorization.id,
    //   dimensionType: props.targetType,
    //   dimensionTypeName: '用户',
    //   dimensionTarget: props.targetId,
    //   dimensionTargetName: '用户名',
    //   state: 1,
    //   actions: (authorization.actions || []).map((i: any) => i.action),
    //   id: 'test',
    //   merge: true,
    //   dataAccesses: (authorization.fieldAccess || []).map((i: any) => {
    //     return {
    //       action: i.name,
    //       type: 'DENY_FIELDS',
    //       describe: '不能操作字段',
    //       config: {

    //       }
    //     }
    //   })
    // }
  };

  return (
    <Drawer title="授权" visible width="50VW" onClose={() => props.close()}>
      <div>{JSON.stringify(targetAutz)}</div>
      <Form>
        <Form.Item label="被授权主体">
          {getFieldDecorator('targetId', {
            rules: [{ required: true }],
            initialValue: props.target.id ? props.target.name : '',
          })(
            <Select mode="multiple" disabled={!!props.target.id}>
              {Array.from(new Set<string>(dimensionList.map((item: any) => item.typeName))).map(
                type => {
                  const typeData = groupBy(dimensionList, item => item.typeName)[type];
                  return (
                    <Select.OptGroup label={type} key={type}>
                      {typeData.map((e: any) => (
                        <Select.Option value={e.id} key={e.id}>
                          {e.name}
                        </Select.Option>
                      ))}
                    </Select.OptGroup>
                  );
                },
              )}
            </Select>,
          )}
        </Form.Item>
        <Form.Item label="选择权限">
          <Input.Group compact style={{ marginBottom: '10px' }}>
            <Select
              style={{ width: '15%' }}
              defaultValue="all"
              onChange={(value: string) => setPermissionType(value)}
            >
              <Select.Option value="all">全部</Select.Option>
              <Select.Option value="default">默认</Select.Option>
              <Select.Option value="system">系统</Select.Option>
              <Select.Option value="biz">业务功能</Select.Option>
              <Select.Option value="open-api">OpenAPI</Select.Option>
            </Select>
            <Input.Search
              style={{ width: '85%' }}
              placeholder="请输入权限名称"
              onChange={event => {
                setSearchText(event.target.value);
              }}
            />
            {/* <Button type="primary" style={{ width: '5%' }}><Icon type='search' /></Button> */}
          </Input.Group>
          <Table
            rowKey="id"
            style={{ height: '65vh', overflow: 'auto' }}
            pagination={false}
            columns={[
              {
                dataIndex: 'name',
                title: '权限名称',
              },
              {
                dataIndex: 'actions',
                title: '权限操作',
                render: (text: { action: string; name: string }[], record: any) => {
                  const { id } = record;

                  const tempText = Object.assign([], text || []);
                  const temp = targetAutz.find(item => item.permission === id) || {};
                  return (
                    <div className={styles.permissionForm}>
                      <Form.Item>
                        {getFieldDecorator(`permissions.${id}`, {
                          initialValue: temp.actions,
                        })(
                          <Checkbox.Group
                            onChange={e => {
                              if (!temp.permission) {
                                targetAutz.push({
                                  id: record.id,
                                  permission: record.id,
                                  actions: e,
                                });
                                setTargetAutz(cloneDeep([...targetAutz]));
                              } else {
                                temp.actions = e;
                                const t = targetAutz.filter(i => i.permission !== id);
                                setTargetAutz(cloneDeep([temp, ...t]));
                              }
                            }}
                            options={tempText.map((e: { action: string; name: string }) => ({
                              label: e.name,
                              value: e.action,
                            }))}
                          />,
                        )}
                      </Form.Item>
                    </div>
                  );
                },
              },
              {
                dataIndex: 'properties',
                title: '操作',
                render: (text, record: any) => {
                  const autz = targetAutz.find(item => item.permission === record.id);
                  return (
                    <Fragment>
                      {autz && autz.actions.length === record.actions.length ? (
                        <a
                          onClick={() => {
                            const temp = targetAutz.filter(item => item.permission !== record.id);
                            setTargetAutz(cloneDeep(temp));
                          }}
                        >
                          取消全选
                        </a>
                      ) : (
                        <a
                          onClick={() => {
                            if (autz) {
                              const temp = targetAutz.filter(item => item.permission !== record.id);
                              autz.actions = record.actions.map((i: any) => i.action);
                              setTargetAutz(cloneDeep([...temp, autz]));
                            } else {
                              targetAutz.push({
                                id: record.id,
                                permission: record.id,
                                actions: record.actions.map((i: any) => i.action),
                              });
                              setTargetAutz(cloneDeep(targetAutz));
                            }
                          }}
                        >
                          全选
                        </a>
                      )}

                      {((text && text.supportDataAccessTypes) || []).some(
                        (i: string) => i === 'DENY_FIELDS',
                      ) && (
                        <>
                          <Divider type="vertical" />

                          <a
                            onClick={() => {
                              setDataAccessVisible(true);
                              setCheckPermission({ ...record, autz });
                            }}
                          >
                            数据权限
                          </a>
                        </>
                      )}
                    </Fragment>
                  );
                },
              },
            ]}
            dataSource={
              // eslint-disable-next-line no-nested-ternary
              permissionType !== 'all'
                ? searchText.length > 0
                  ? JSON.parse(JSON.stringify(permissionList))
                      .filter((item: any) => (item.properties || {}).type === permissionType)
                      .filter((item: any) => item.name.indexOf(searchText) > -1)
                  : JSON.parse(JSON.stringify(permissionList)).filter(
                      (item: any) => (item.properties || {}).type === permissionType,
                    )
                : searchText.length > 0
                ? JSON.parse(JSON.stringify(permissionList)).filter(
                    (item: any) => item.name.indexOf(searchText) > -1,
                  )
                : permissionList
            }
          />
        </Form.Item>
      </Form>
      <div
        style={{
          position: 'absolute',
          right: 0,
          bottom: 0,
          width: '100%',
          borderTop: '1px solid #e9e9e9',
          padding: '10px 16px',
          background: '#fff',
          textAlign: 'right',
        }}
      >
        <Button
          onClick={() => {
            props.close();
          }}
          style={{ marginRight: 8 }}
        >
          关闭
        </Button>
        <Button
          onClick={() => {
            autzSetting();
          }}
          type="primary"
        >
          保存
        </Button>
      </div>
      {dataAccessVisible && (
        <DataAccess
          checkPermission={checkPermission}
          close={() => setDataAccessVisible(false)}
          save={(item: any) => {
            saveDataAccess(item);
          }}
        />
      )}
    </Drawer>
  );
};
export default Form.create<Props>()(Authorization);

// src/components/Authorization/index.vue
<template>
  <a-drawer title="授权" v-model:visible="modalVisible" @close="okBtn" :width="720">
    <a-form :model="form" :rules="rules" layout="vertical" style="margin-bottom: 50px">
      <a-form-item label="被授权主体" name="target">
        <a-input v-model:value="form.target" :disabled="true" />
      </a-form-item>
      <a-form-item label="筛选权限">
        <a-input-group compact>
          <a-select v-model:value="form.type" style="width: 20%" @change="typeChange">
            <a-select-option value="all">全部</a-select-option>
            <a-select-option value="default">默认</a-select-option>
            <a-select-option value="system">系统</a-select-option>
            <a-select-option value="business">业务功能</a-select-option>
            <a-select-option value="open-api">OpenAPI</a-select-option>
            <a-select-option value="tenant">多租户</a-select-option>
          </a-select>
          <a-input-search @search="onSearch" style="width: 80%" placeholder="请输入权限名称" />
        </a-input-group>
      </a-form-item>
      <a-table rowKey="id" :columns="columns" :pagination="false" :dataSource="permissionList" :loading="loading">
        <template #actions="{ record }">
          <a-checkbox-group v-model:value="checkDimension[record.id]">
            <template v-for="item in record.actions" :key="item.action">
              <a-checkbox :value="item.action">{{item.name}}</a-checkbox>
            </template>
          </a-checkbox-group>
        </template>
        <template #operation="{ record }">
          <a @click="checkCancel(record.id)" v-if="checkDimension[record.id] && record.actions && checkDimension[record.id].length === record.actions.length">取消全选</a>
          <a v-else @click="checkAll(record.id, record.actions)">全选</a>
        </template>
      </a-table>
    </a-form>
    <div
      :style="{
        position: 'absolute',
        right: 0,
        bottom: 0,
        width: '100%',
        borderTop: '1px solid #e9e9e9',
        padding: '10px 16px',
        background: '#fff',
        textAlign: 'right',
        zIndex: 1,
      }"
    >
      <a-button style="margin-right: 8px" @click="okBtn">取消</a-button>
      <a-button type="primary" @click="submit">确定</a-button>
    </div>
  </a-drawer>
</template>

<script lang="ts">
import { defineComponent, reactive, ref, toRaw, watch } from 'vue'
import { listNoPaging, getAutzSetting, saveAutz } from './service'
import encodeQuery from '@/utils/encodeQuery'
import _ from 'lodash'
import { message } from 'ant-design-vue'
export default defineComponent({
  name: 'Authorization',
  props: ['modelValue', 'data'],
  emits: ['update:modelValue'],
  setup (props, { emit }) {
    const modalVisible = ref<boolean>(false)
    const form = reactive({
      target: '',
      type: 'all'
    })
    const loading = ref<boolean>(true)
    const permissionList = reactive([])
    const permissionAllList = reactive([])
    const checkDimension = reactive<any>({})
    const rules = {
      target: [{ required: true, message: '请输入' }]
    }
    const columns = [
      {
        title: '权限名称',
        dataIndex: 'name',
        key: 'name'
      },
      {
        title: '权限操作',
        dataIndex: 'actions',
        key: 'actions',
        slots: { customRender: 'actions' }
      },
      {
        title: '操作',
        dataIndex: 'operation',
        key: 'operation',
        width: 100,
        slots: { customRender: 'operation' }
      }
    ]
    watch(() => props.modelValue, (newValue) => {
      modalVisible.value = newValue
      if (newValue) {
        form.target = props.data.name
        loading.value = true
        listNoPaging().then(resp => {
          if (resp.data.status === 200) {
            const temp: any[] = resp.data.result
            const list = temp.filter(item => (item.actions || []).length > 0)
            Object.assign(permissionAllList, list)
            Object.assign(permissionList, list)
            loading.value = false
          }
        })
      }
    })
    watch(() => props.data, (newValue) => {
      if (newValue) {
        getAutzSetting(encodeQuery({
          paging: false,
          terms: {
            dimensionTarget: props.data.id
          }
        })).then(resp => {
          if (resp.data.status === 200) {
            resp.data.result.map((item: any) => {
              checkDimension[item.permission] = item.actions
            })
          }
        })
      }
    })
    const okBtn = () => {
      modalVisible.value = false
      emit('update:modelValue', false)
    }
    const checkAll = (id: string, actions: any[]) => {
      checkDimension[id] = _.map(actions, 'action')
    }
    const checkCancel = (id: string) => {
      checkDimension[id] = []
    }
    const typeChange = (e: string) => {
      permissionList.splice(0, permissionList.length)
      if (e === 'all') {
        Object.assign(permissionList, permissionAllList)
      } else {
        const list = permissionAllList.filter((item: any) => {
          return item && item.properties && (item.properties?.type || []).includes(e)
        })
        Object.assign(permissionList, list)
      }
    }
    const onSearch = (searchValue: string) => {
      permissionList.splice(0, permissionList.length)
      const list = permissionAllList.filter((item: any) => {
        return item.name.indexOf(searchValue) !== -1
      })
      Object.assign(permissionList, list)
    }
    const submit = () => {
      const permissionList: any[] = []
      Object.keys(checkDimension).forEach(key => {
        if (toRaw(checkDimension[key]).length > 0) {
          permissionList.push({
            id: key,
            actions: toRaw(checkDimension[key])
          })
        }
      })
      const data = {
        targetId: props.data.id,
        targetType: props.data.targetType,
        permissionList
      }
      saveAutz(data).then(resp => {
        if (resp.data.status === 200) {
          message.success('授权成功')
        }
      })
    }
    return {
      modalVisible,
      okBtn,
      form,
      rules,
      columns,
      permissionList,
      checkDimension,
      checkAll,
      checkCancel,
      submit,
      typeChange,
      onSearch,
      loading
    }
  }
})
</script>
