// src/pages/device/product/save/definition/index.tsx
import React from 'react';
import { Tabs, Card } from 'antd';
import Property from './Properties';
import Functions from './Functions';
import Events from './Events';
import Tags from '@/pages/device/product/save/definition/Tags';

interface Props {
  saveProperty: Function;
  saveFunctions: Function;
  saveEvents: Function;
  saveTags: Function;
  propertyData: any;
  functionsData: any;
  eventsData: any;
  tagsData: any;
}

const Definition: React.FC<Props> = props => (
  <Card>
    <Tabs defaultActiveKey="1" tabPosition="left">
      <Tabs.TabPane tab="属性定义" key="1">
        <Property
          data={props.propertyData}
          save={(data: any) => {
            props.saveProperty(data);
          }}
        />
      </Tabs.TabPane>
      <Tabs.TabPane tab="功能定义" key="2">
        <Functions
          data={props.functionsData}
          save={(data: any) => {
            props.saveFunctions(data);
          }}
        />
      </Tabs.TabPane>
      <Tabs.TabPane tab="事件定义" key="3">
        <Events
          data={props.eventsData}
          save={(data: any) => {
            props.saveEvents(data);
          }}
        />
      </Tabs.TabPane>
      <Tabs.TabPane tab="标签定义" key="4">
        <Tags
          data={props.tagsData}
          save={(data: any) => {
            props.saveTags(data);
          }}
        />
      </Tabs.TabPane>
    </Tabs>
  </Card>
);

export default Definition;

// src/views/pages/device/product/detail/definition/index.vue
<template>
  <a-tabs tab-position="top" type="card">
    <a-tab-pane key="1" tab="属性定义">
      <Properties />
    </a-tab-pane>
    <a-tab-pane key="2" tab="功能定义">
      <Functions />
    </a-tab-pane>
    <a-tab-pane key="3" tab="事件定义">
      <Events />
    </a-tab-pane>
    <a-tab-pane key="4" tab="标签定义">
      <Tags />
    </a-tab-pane>
    <template #tabBarExtraContent>
      <a-space>
        <a-button>快速导入</a-button>
        <a-button>物模型TSL</a-button>
      </a-space>
    </template>
  </a-tabs>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import Properties from './properties/index.vue'
import Functions from './functions/index.vue'
import Events from './events/index.vue'
import Tags from './tags/index.vue'
export default defineComponent({
  components: { Events, Properties, Functions, Tags },
  setup () {
    return {}
  }
})
</script>
