// src/components/Authorization/index.vue
<template>
  <a-drawer title="授权" v-model:visible="modalVisible" @close="okBtn" :width="720">
    <a-form :model="form" :rules="rules" layout="vertical" style="margin-bottom: 50px">
      <a-form-item label="被授权主体" name="target">
        <a-input v-model:value="form.target" :disabled="true" />
      </a-form-item>
      <a-form-item label="筛选权限">
        <a-input-group compact>
          <a-select v-model:value="form.type" style="width: 20%" @change="typeChange">
            <a-select-option value="all">全部</a-select-option>
            <a-select-option value="default">默认</a-select-option>
            <a-select-option value="system">系统</a-select-option>
            <a-select-option value="business">业务功能</a-select-option>
            <a-select-option value="open-api">OpenAPI</a-select-option>
            <a-select-option value="tenant">多租户</a-select-option>
          </a-select>
          <a-input-search @search="onSearch" style="width: 80%" placeholder="请输入权限名称" />
        </a-input-group>
      </a-form-item>
      <a-table rowKey="id" :columns="columns" :pagination="false" :dataSource="permissionList" :loading="loading">
        <template #actions="{ record }">
          <a-checkbox-group v-model:value="checkDimension[record.id]">
            <template v-for="item in record.actions" :key="item.action">
              <a-checkbox :value="item.action">{{item.name}}</a-checkbox>
            </template>
          </a-checkbox-group>
        </template>
        <template #operation="{ record }">
          <a @click="checkCancel(record.id)" v-if="checkDimension[record.id] && record.actions && checkDimension[record.id].length === record.actions.length">取消全选</a>
          <a v-else @click="checkAll(record.id, record.actions)">全选</a>
        </template>
      </a-table>
    </a-form>
    <div
      :style="{
        position: 'absolute',
        right: 0,
        bottom: 0,
        width: '100%',
        borderTop: '1px solid #e9e9e9',
        padding: '10px 16px',
        background: '#fff',
        textAlign: 'right',
        zIndex: 1,
      }"
    >
      <a-button style="margin-right: 8px" @click="okBtn">取消</a-button>
      <a-button type="primary" @click="submit">确定</a-button>
    </div>
  </a-drawer>
</template>

<script lang="ts">
import { defineComponent, reactive, ref, toRaw, watch } from 'vue'
import { listNoPaging, getAutzSetting, saveAutz } from './service'
import encodeQuery from '@/utils/encodeQuery'
import _ from 'lodash'
import { message } from 'ant-design-vue'
export default defineComponent({
  name: 'Authorization',
  props: ['modelValue', 'data'],
  emits: ['update:modelValue'],
  setup (props, { emit }) {
    const modalVisible = ref<boolean>(false)
    const form = reactive({
      target: '',
      type: 'all'
    })
    const loading = ref<boolean>(true)
    const permissionList = reactive([])
    const permissionAllList = reactive([])
    const checkDimension = reactive<any>({})
    const rules = {
      target: [{ required: true, message: '请输入' }]
    }
    const columns = [
      {
        title: '权限名称',
        dataIndex: 'name',
        key: 'name'
      },
      {
        title: '权限操作',
        dataIndex: 'actions',
        key: 'actions',
        slots: { customRender: 'actions' }
      },
      {
        title: '操作',
        dataIndex: 'operation',
        key: 'operation',
        width: 100,
        slots: { customRender: 'operation' }
      }
    ]
    watch(() => props.modelValue, (newValue) => {
      modalVisible.value = newValue
      if (newValue) {
        form.target = props.data.name
        loading.value = true
        listNoPaging().then(resp => {
          if (resp.data.status === 200) {
            const temp: any[] = resp.data.result
            const list = temp.filter(item => (item.actions || []).length > 0)
            Object.assign(permissionAllList, list)
            Object.assign(permissionList, list)
            loading.value = false
          }
        })
      }
    })
    watch(() => props.data, (newValue) => {
      if (newValue) {
        getAutzSetting(encodeQuery({
          paging: false,
          terms: {
            dimensionTarget: props.data.id
          }
        })).then(resp => {
          if (resp.data.status === 200) {
            resp.data.result.map((item: any) => {
              checkDimension[item.permission] = item.actions
            })
          }
        })
      }
    })
    const okBtn = () => {
      modalVisible.value = false
      emit('update:modelValue', false)
    }
    const checkAll = (id: string, actions: any[]) => {
      checkDimension[id] = _.map(actions, 'action')
    }
    const checkCancel = (id: string) => {
      checkDimension[id] = []
    }
    const typeChange = (e: string) => {
      permissionList.splice(0, permissionList.length)
      if (e === 'all') {
        Object.assign(permissionList, permissionAllList)
      } else {
        const list = permissionAllList.filter((item: any) => {
          return item && item.properties && (item.properties?.type || []).includes(e)
        })
        Object.assign(permissionList, list)
      }
    }
    const onSearch = (searchValue: string) => {
      permissionList.splice(0, permissionList.length)
      const list = permissionAllList.filter((item: any) => {
        return item.name.indexOf(searchValue) !== -1
      })
      Object.assign(permissionList, list)
    }
    const submit = () => {
      const permissionList: any[] = []
      Object.keys(checkDimension).forEach(key => {
        if (toRaw(checkDimension[key]).length > 0) {
          permissionList.push({
            id: key,
            actions: toRaw(checkDimension[key])
          })
        }
      })
      const data = {
        targetId: props.data.id,
        targetType: props.data.targetType,
        permissionList
      }
      saveAutz(data).then(resp => {
        if (resp.data.status === 200) {
          message.success('授权成功')
        }
      })
    }
    return {
      modalVisible,
      okBtn,
      form,
      rules,
      columns,
      permissionList,
      checkDimension,
      checkAll,
      checkCancel,
      submit,
      typeChange,
      onSearch,
      loading
    }
  }
})
</script>

// src/pages/system/User/Authorization/index.tsx
import { observer } from '@formily/react';
import type { TableColumnsType } from 'antd';
import { Button, Checkbox, Col, Form, Input, Row, Select, Table } from 'antd';
import Service from '@/pages/system/User/Authorization/service';
import { useEffect } from 'react';
import { model } from '@formily/reactive';
import encodeQuery from '@/utils/encodeQuery';
import { map, scan, takeLast } from 'rxjs/operators';
import db from '@/pages/system/User/Authorization/db';
import { toArray } from 'rxjs';

const service = new Service();

const AuthorizationModel = model<{
  data: PermissionItem[];
  checkedPermission: Map<string, Set<string>>;
}>({
  data: [],
  checkedPermission: new Map(),
});
const Authorization = observer(() => {
  const [form] = Form.useForm();
  useEffect(() => {
    service
      .getPermission()
      .pipe(
        map((item) => {
          const type = item.properties?.type;
          return { ...item, type };
        }),
        toArray(),
      )
      .subscribe(async (permission: any) => {
        db.table('permission').clear();
        db.table('permission').bulkAdd(permission);
        AuthorizationModel.data = await db.table('permission').reverse().sortBy('name');
      });
    service
      .getAutzSetting(
        encodeQuery({
          paging: false,
          terms: {
            dimensionTarget: '11f0075aa18835be6217f52902985c75',
          },
        }),
      )
      .pipe(
        map((item: AuthorizationItem) => ({ key: item.permission, actions: item.actions })),
        scan((result, value) => {
          // eslint-disable-next-line no-param-reassign
          result[value.key] = value.actions.map((ac) => `${value.key}@${ac}`);
          return result;
        }, {}),
        takeLast(1),
      )
      .subscribe((data) => {
        form.setFieldsValue(data);
      });
  }, []);

  const columns: TableColumnsType<PermissionItem> = [
    {
      title: '名称',
      dataIndex: 'name',
      width: 200,
    },
    {
      title: '权限操作',
      dataIndex: 'actions',
      render: (text: { action: string; name: string; id: string }[], record) => (
        <Form.Item name={record.id}>
          <Checkbox.Group
            name={record.id}
            onChange={(data) => {
              AuthorizationModel.checkedPermission.set(
                record.id,
                new Set<string>(data as string[]),
              );
            }}
            options={text.map((item) => ({
              label: item.name,
              value: `${record.id}@${item.action}`,
              key: item.id,
            }))}
          />
        </Form.Item>
      ),
    },
    {
      title: '操作',
      width: 200,
      dataIndex: 'option',
      render: (text, record) => (
        <>
          <Checkbox
            onChange={(e) => {
              form.setFieldsValue({
                [record.id]: e.target.checked
                  ? record.actions.map((item) => `${record.id}@${item.action}`)
                  : [],
              });
            }}
          >
            全选
          </Checkbox>
        </>
      ),
    },
  ];
  return (
    <>
      <Form
        onFinish={(data) => {
          console.log(data, 'd');
        }}
        size={'small'}
        form={form}
        wrapperCol={{ span: 20 }}
        labelCol={{ span: 2 }}
      >
        <Form.Item label="被授权主体">
          <Select mode="multiple" />
        </Form.Item>
        <Form.Item label="筛选权限">
          <Input.Group>
            <Row>
              <Col span={4}>
                <Select
                  onSelect={async (value: string) => {
                    AuthorizationModel.data = await db
                      .table('permission')
                      .filter((item) =>
                        value === 'all' ? item : (item.type || []).includes(value),
                      )
                      .distinct()
                      .reverse()
                      .sortBy('name');
                  }}
                  style={{ width: '100%' }}
                  options={[
                    { label: '全部', value: 'all' },
                    { label: '默认', value: 'default' },
                    { label: '系统', value: 'system' },
                    { label: '业务功能', value: 'business' },
                    { label: 'OpenAPI', value: 'open-api' },
                    { label: '多租户', value: 'tenant' },
                  ]}
                />
              </Col>
              <Col span={20}>
                <Input.Search
                  placeholder="请输入权限名称"
                  onSearch={async (value) => {
                    AuthorizationModel.data = await db
                      .table('permission')
                      .where('name')
                      .startsWith(value)
                      .distinct()
                      .reverse()
                      .sortBy('name');
                  }}
                />
              </Col>
            </Row>
          </Input.Group>
        </Form.Item>
        <Table
          style={{ height: '75vh', overflow: 'auto' }}
          size={'small'}
          rowKey="id"
          pagination={false}
          columns={columns}
          dataSource={AuthorizationModel.data}
        />
      </Form>
      <div
        style={{
          position: 'absolute',
          right: 0,
          bottom: 0,
          width: '100%',
          borderTop: '1px solid #e9e9e9',
          padding: '10px 16px',
          background: '#fff',
          textAlign: 'right',
        }}
      >
        <Button
          onClick={async () => {
            // props.close();
          }}
          style={{ marginRight: 8 }}
        >
          关闭
        </Button>
        <Button onClick={form.submit} type="primary">
          保存
        </Button>
      </div>
    </>
  );
});

export default Authorization;
