// src/views/pages/system/permission/index.vue
<template>
  <page-container title="权限管理">
    <BaseCrud :model-visible="false" :form-data="{}" :model="model" :columns="columns" title="权限列表" :service="service" :default-params="defaultParams">
      <template #extra>
        <a-space>
          <a-button @click="addBtn" type="primary">新增</a-button>
          <a-upload
            action='http://demo.jetlinks.cn/jetlinks/file/static'
            :headers="headers"
            :showUploadList="false"
            accept=".json"
            :before-upload="importBtn"
          >
            <a-button><ImportOutlined />导入</a-button>
          </a-upload>
          <a-button @click="exportBtn"><ExportOutlined />导出</a-button>
        </a-space>
      </template>
      <template #status="slotProps">
        <template v-if="slotProps.value === 1">
          <a-tag color="#108ee9">正常</a-tag>
        </template>
        <template v-else>
          <a-tag color="#f50">禁用</a-tag>
        </template>
      </template>
      <template #action="{ record }">
        <a-space>
          <a @click="editBtn(record)">编辑</a>
          <a-popconfirm
            title="确认删除?"
            ok-text="确认"
            cancel-text="取消"
            @confirm="delBtn(record.id)"
          >
            <a>删除</a>
          </a-popconfirm>
        </a-space>
      </template>
    </BaseCrud>
  </page-container>
  <Save v-model="visible" :data="current" @ok-btn="okBtn" />
</template>

<script lang="ts">
import { downloadObject, headers } from '@/utils/utils'
import { defineComponent, ref } from 'vue'
import BaseCrud from '@/components/BaseCrud/index.vue'
import Save from './save/index.vue'
import BaseService from '@/utils/base-service'
import { message } from 'ant-design-vue'
export type PermissionItem = {
  id: string;
  name: string;
  parents: any[];
  actions: any[];
  properties: any;
  status?: number;
  optionalFields: any[]
};

export default defineComponent({
  components: {
    BaseCrud,
    Save
  },
  setup () {
    const service = new BaseService<PermissionItem>('permission')
    const columns = [
      {
        title: 'ID',
        dataIndex: 'id',
        key: 'id',
        search: true,
        searchParams: {
          transform: (value: string) => ({ id$LIKE: value })
        }
      },
      {
        title: '名称',
        dataIndex: 'name',
        key: 'name',
        search: true,
        searchParams: {
          transform: (value: string) => ({ name$LIKE: value })
        }
      },
      {
        title: '状态',
        slots: true,
        dataIndex: 'status',
        key: 'status'
      },
      {
        title: '操作',
        dataIndex: 'action',
        key: 'action',
        slots: true
      }
    ]
    const visible = ref<boolean>(false)
    const current = ref()
    const model = ref<'edit' | 'preview' | 'add' | 'refresh'>('preview')
    const defaultParams = {
      pageIndex: 0,
      pageSize: 10,
      sorts: {
        createTime: 'desc'
      }
    }
    const addBtn = () => {
      visible.value = true
      model.value = 'add'
      current.value = {
        id: '',
        name: '',
        status: 1,
        properties: {
          type: []
        },
        parents: [],
        actions: [],
        optionalFields: []
      }
    }
    const editBtn = (data: any) => {
      visible.value = true
      model.value = 'edit'
      current.value = data
    }
    const okBtn = (data: any) => {
      service.update(data).then(resp => {
        if (resp.data.status === 200) {
          message.success('操作成功')
          model.value = 'refresh'
        }
      })
    }
    const delBtn = (id: string) => {
      service.remove(id).then(res => {
        if (res.data.status === 200) {
          model.value = 'refresh'
        }
      })
    }
    const importBtn = (file: any) => {
      const reader = new FileReader()
      reader.readAsText(file)
      reader.onload = (result: any) => {
        try {
          const data = JSON.parse(result.target.result)
          service.update(data).then(resp => {
            if (resp.data.status === 200) {
              message.success('操作成功')
              model.value = 'refresh'
            }
          })
        } catch (error) {
          message.error('导入失败，请重试！')
        }
      }
    }
    const exportBtn = () => {
      service.queryNoPaging({}).then(resp => {
        if (resp.data.status === 200) {
          downloadObject(resp.data.result, '权限数据')
          message.success('导出成功')
        } else {
          message.error('导出错误')
        }
      })
    }
    return {
      columns,
      service,
      defaultParams,
      model,
      addBtn,
      editBtn,
      delBtn,
      visible,
      okBtn,
      current,
      importBtn,
      exportBtn,
      headers
    }
  }
})
</script>

// src/pages/system/Permission/index.tsx
import { PageContainer } from '@ant-design/pro-layout';
import React, { useRef, useState } from 'react';
import {
  CloseCircleOutlined,
  DeleteOutlined,
  EditOutlined,
  PlayCircleOutlined,
  PlusOutlined,
} from '@ant-design/icons';
import { Badge, Button, Dropdown, Menu, message, Popconfirm, Tooltip, Upload } from 'antd';
import type { ActionType, ProColumns } from '@jetlinks/pro-table';
import { useIntl } from '@@/plugin-locale/localeExports';
import type { PermissionItem } from '@/pages/system/Permission/typings';
import Service from '@/pages/system/Permission/service';
import { observer } from '@formily/react';
import SearchComponent from '@/components/SearchComponent';
import ProTable from '@jetlinks/pro-table';
import Save from './Save';
import SystemConst from '@/utils/const';
import { downloadObject } from '@/utils/util';
import Token from '@/utils/token';

export const service = new Service('permission');
const Permission: React.FC = observer(() => {
  const intl = useIntl();
  const actionRef = useRef<ActionType>();

  const [param, setParam] = useState({});
  const [model, setMode] = useState<'add' | 'edit' | 'query'>('query');
  const [current, setCurrent] = useState<Partial<PermissionItem>>({});

  const edit = async (record: PermissionItem) => {
    setMode('edit');
    setCurrent(record);
  };

  const menu = (
    <Menu>
      <Menu.Item key="import">
        <Upload
          action={`/${SystemConst.API_BASE}/file/static`}
          headers={{
            'X-Access-Token': Token.get(),
          }}
          showUploadList={false}
          accept=".json"
          beforeUpload={(file) => {
            const reader = new FileReader();
            reader.readAsText(file);
            reader.onload = (result: any) => {
              try {
                const data = JSON.parse(result.target.result);
                service.batchAdd(data).subscribe((resp) => {
                  if (resp.status === 200) {
                    message.success('导入成功');
                    actionRef.current?.reload();
                  }
                });
              } catch (error) {
                message.error('导入失败，请重试！');
              }
            };
          }}
        >
          <Button>导入</Button>
        </Upload>
      </Menu.Item>
      <Menu.Item key="export">
        <Popconfirm
          title={'确认导出？'}
          onConfirm={() => {
            service.getPermission({ ...param, paging: false }).subscribe((resp) => {
              if (resp.status === 200) {
                downloadObject(resp.result, '权限数据');
                message.success('导出成功');
              } else {
                message.error('导出错误');
              }
            });
          }}
        >
          <Button>导出</Button>
        </Popconfirm>
      </Menu.Item>
    </Menu>
  );

  const columns: ProColumns<PermissionItem>[] = [
    {
      title: intl.formatMessage({
        id: 'pages.system.permission.id',
        defaultMessage: '标识',
      }),
      dataIndex: 'id',
      // copyable: true,
      ellipsis: true,
      // sorter: true,
      defaultSortOrder: 'ascend',
    },
    {
      title: intl.formatMessage({
        id: 'pages.table.name',
        defaultMessage: '名称',
      }),
      dataIndex: 'name',
      // copyable: true,
      ellipsis: true,
    },
    {
      title: intl.formatMessage({
        id: 'pages.searchTable.titleStatus',
        defaultMessage: '状态',
      }),
      dataIndex: 'status',
      // filters: true,
      valueType: 'select',
      valueEnum: {
        1: {
          text: intl.formatMessage({
            id: 'pages.searchTable.titleStatus.normal',
            defaultMessage: '正常',
          }),
          status: 1,
        },
        0: {
          text: intl.formatMessage({
            id: 'pages.searchTable.titleStatus.disable',
            defaultMessage: '禁用',
          }),
          status: 0,
        },
      },
      render: (text, record) => (
        <Badge status={record.status === 1 ? 'success' : 'error'} text={text} />
      ),
    },
    {
      title: intl.formatMessage({
        id: 'pages.data.option',
        defaultMessage: '操作',
      }),
      valueType: 'option',
      width: 200,
      render: (text, record) => [
        <a
          key="editable"
          onClick={() => {
            edit(record);
          }}
        >
          <Tooltip
            title={intl.formatMessage({
              id: 'pages.data.option.edit',
              defaultMessage: '编辑',
            })}
          >
            <EditOutlined />
          </Tooltip>
        </a>,
        <a key="view">
          <Popconfirm
            title={intl.formatMessage({
              id: 'pages.data.option.disabled.tips',
              defaultMessage: '确认禁用？',
            })}
            onConfirm={async () => {
              await service.update({
                ...record,
                id: record.id,
                status: record.status ? 0 : 1,
              });
              message.success(
                intl.formatMessage({
                  id: 'pages.data.option.success',
                  defaultMessage: '操作成功!',
                }),
              );
              actionRef.current?.reload();
            }}
          >
            <Tooltip
              title={intl.formatMessage({
                id: `pages.data.option.${record.status ? 'disabled' : 'enabled'}`,
                defaultMessage: record.status ? '禁用' : '启用',
              })}
            >
              {record.status ? <CloseCircleOutlined /> : <PlayCircleOutlined />}
            </Tooltip>
          </Popconfirm>
        </a>,
        <Tooltip
          key="delete"
          title={
            record.status === 0
              ? intl.formatMessage({
                  id: 'pages.data.option.remove',
                  defaultMessage: '删除',
                })
              : '请先禁用该权限，再删除。'
          }
        >
          <Button type="link" style={{ padding: 0 }} disabled={record.status === 1}>
            <Popconfirm
              title={intl.formatMessage({
                id: 'pages.data.option.remove.tips',
                defaultMessage: '确认删除？',
              })}
              onConfirm={async () => {
                await service.remove(record.id);
                message.success(
                  intl.formatMessage({
                    id: 'pages.data.option.success',
                    defaultMessage: '操作成功!',
                  }),
                );
                actionRef.current?.reload();
              }}
            >
              <DeleteOutlined />
            </Popconfirm>
          </Button>
        </Tooltip>,
      ],
    },
  ];

  return (
    <PageContainer>
      <SearchComponent<PermissionItem>
        field={columns}
        target="permission"
        onSearch={(data) => {
          // 重置分页数据
          actionRef.current?.reset?.();
          setParam(data);
        }}
        onReset={() => {
          // 重置分页及搜索参数
          actionRef.current?.reset?.();
          setParam({});
        }}
      />
      <ProTable<PermissionItem>
        actionRef={actionRef}
        params={param}
        columns={columns}
        search={false}
        headerTitle={'权限列表'}
        request={async (params) =>
          service.query({ ...params, sorts: [{ name: 'id', order: 'asc' }] })
        }
        toolBarRender={() => [
          <Button
            onClick={() => {
              setMode('add');
            }}
            key="button"
            icon={<PlusOutlined />}
            type="primary"
          >
            {intl.formatMessage({
              id: 'pages.data.option.add',
              defaultMessage: '新增',
            })}
          </Button>,
          <Dropdown key={'more'} overlay={menu} placement="bottom">
            <Button>批量操作</Button>
          </Dropdown>,
        ]}
      />
      <Save
        model={model}
        close={() => {
          setMode('query');
          actionRef.current?.reload();
        }}
        data={current}
      />
    </PageContainer>
  );
});

export default Permission;
