// src/pages/device/product/save/Detail.tsx
import React, { useEffect, useState } from 'react';
import { Badge, Button, Card, Descriptions, Icon, message, Popconfirm, Row, Spin, Tabs, Tooltip } from 'antd';
import { PageHeaderWrapper } from '@ant-design/pro-layout';
import { connect } from 'dva';
import { router } from 'umi';
import { DeviceProduct } from '../data.d';
import Definition from './definition';
import { ConnectState, Dispatch } from '@/models/connect';
import apis from '@/services';
import Save from '.';
import numeral from 'numeral';
import encodeQueryParam from '@/utils/encodeParam';
import Alarm from '@/pages/device/alarm';
import Configuration from "@/pages/device/product/save/configuration";

interface Props {
  dispatch: Dispatch;
  location: Location;
  close: Function;
  save: Function;
}

interface State {
  basicInfo: Partial<DeviceProduct>;
  saveVisible: boolean;
  config: any;
  orgInfo: any;
  deviceCount: number;
  spinning: boolean;
  units: any;
}

const Detail: React.FC<Props> = props => {
  const initState: State = {
    basicInfo: {},
    saveVisible: false,
    config: [],
    orgInfo: {},
    deviceCount: 0,
    spinning: true,
    units: {},
  };
  const {
    dispatch,
    location: { pathname },
  } = props;
  const [events, setEvents] = useState<any[]>([]);
  const [functions, setFunctions] = useState<any[]>([]);
  const [properties, setProperties] = useState<any[]>([]);
  const [tags, setTags] = useState<any[]>([]);
  const [basicInfo, setBasicInfo] = useState(initState.basicInfo);
  const [saveVisible, setSaveVisible] = useState(initState.saveVisible);
  const [config, setConfig] = useState(initState.config);
  const [orgInfo] = useState(initState.orgInfo);
  const [deviceCount, setDeviceCount] = useState(initState.deviceCount);
  const [spinning, setSpinning] = useState(initState.spinning);
  const [units, setUnits] = useState(initState.units);
  const [updateVisible, setUpdateVisible] = useState(false);
  const [productId, setProductId] = useState("");

  const handleSearch = (id?: string) => {
    const list = pathname.split('/');
    const temp = id || list[list.length - 1];
    dispatch({
      type: 'deviceProduct/queryById',
      payload: temp,
      callback: (r: any) => {
        if (r.status === 200) {
          const data = r.result;
          data.orgName = orgInfo[data.orgId];
          setBasicInfo(data);
          setSpinning(false);
          if (data.metadata) {
            const metadata = JSON.parse(data.metadata);
            setEvents(metadata.events);
            setFunctions(metadata.functions);
            setProperties(metadata.properties);
            setTags(metadata.tags);
          }
          // apis.deviceProdcut
          //   .protocolConfiguration(data.messageProtocol, data.transportProtocol)
          //   .then(resp => {
          //     setConfig(resp.result);
          //   });
          apis.deviceProdcut.productConfiguration(data.id).then(resp => {
            setConfig(resp.result);
          })
        }
      },
    });

    apis.deviceInstance.count(encodeQueryParam({ terms: { 'productId': id } }))
      .then(res => {
        if (res.status === 200) {
          setDeviceCount(res.result);
        }
      }).catch();
  };

  useEffect(() => {
    apis.deviceProdcut
      .queryOrganization()
      .then(res => {
        if (res.status === 200) {
          res.result.map((e: any) => (
            orgInfo[e.id] = e.name
          ));
        }
      }).catch(() => {
      });

    apis.deviceProdcut.units().then((response: any) => {
      if (response.status === 200) {
        setUnits(response.result);
      }
    }).catch(() => {
    });

    if (pathname.indexOf('save') > 0) {
      const list = pathname.split('/');
      handleSearch(list[list.length - 1]);
      setProductId(list[list.length - 1]);
    }
  }, []);

  const saveData = (item?: any) => {
    let data: Partial<DeviceProduct>;
    const metadata = JSON.stringify({ events, properties, functions, tags });

    // TODO 这个地方有疑惑，set数据之后此处数据还是未更新。原因待查
    if (item) {
      data = { ...item, metadata };
    } else {
      data = { ...basicInfo, metadata };
    }
    apis.deviceProdcut
      .saveOrUpdate(data)
      .then(r => {
        if (r.status === 200) {
          setSaveVisible(false);
          message.success('保存成功');
          const list = pathname.split('/');
          handleSearch(list[list.length - 1]);
        }
      })
      .catch(() => {
      });
  };

  const updateData = (type: string, item: any, onlySave: boolean) => {
    let metadata = JSON.stringify({ events, properties, functions, tags });
    if (type === 'event') {
      metadata = JSON.stringify({ events: item, properties, functions, tags });
    } else if (type === 'properties') {
      metadata = JSON.stringify({ events, properties: item, functions, tags });
    } else if (type === 'function') {
      metadata = JSON.stringify({ events, properties, functions: item, tags });
    } else if (type === 'tags') {
      metadata = JSON.stringify({ events, properties, functions, tags: item });
    }

    const data = { ...basicInfo, metadata };
    apis.deviceProdcut
      .saveOrUpdate(data)
      .then((re: any) => {
        if (re.status === 200) {
          message.success('保存成功');
          if (!onlySave) {
            deploy(data)
          }
        }
      })
      .catch(() => {
      });
  };

  const deploy = (record: any) => {
    setSpinning(true);
    dispatch({
      type: 'deviceProduct/deploy',
      payload: record.id,
      callback: response => {
        if (response.status === 200) {
          basicInfo.state = 1;
          setBasicInfo(basicInfo);
          message.success('操作成功');
          setSpinning(false);
        }
      },
    });
  };

  const unDeploy = (record: any) => {
    setSpinning(true);
    dispatch({
      type: 'deviceProduct/unDeploy',
      payload: record.id,
      callback: response => {
        if (response.status === 200) {
          basicInfo.state = 0;
          setBasicInfo(basicInfo);
          message.success('操作成功');
          setSpinning(false);
        }
      },
    });
  };

  const updateInfo = (onlySave: boolean, item?: any) => {
    apis.deviceProdcut
      .update(item, basicInfo.id)
      .then((response: any) => {
        if (response.status === 200) {
          message.success('配置信息修改成功');
          setUpdateVisible(false);
          const list = pathname.split('/');
          handleSearch(list[list.length - 1]);
          if (!onlySave) {
            // deploy(basicInfo)
            setSpinning(true);
            dispatch({
              type: 'deviceProduct/unDeploy',
              payload: basicInfo.id,
              callback: res => {
                if (res.status === 200) {
                  basicInfo.state = 0;
                  setBasicInfo(basicInfo);
                  message.success('操作成功');
                  setSpinning(false);
                  const list = pathname.split('/');
                  handleSearch(list[list.length - 1]);
                }
              },
            });
          }
        }
      })
      .catch(() => {
      });
  };

  const content = (
    <div style={{ marginTop: 30 }}>
      <Descriptions column={4}>
        <Descriptions.Item label="设备数量">
          <div>
            {numeral(deviceCount).format('0,0')}
            <a style={{ marginLeft: 10 }}
              onClick={() => {
                router.push(`/device/instance?productId=${basicInfo.id}`);
              }}
            >查看</a>
          </div>
        </Descriptions.Item>
      </Descriptions>
    </div>
  );

  const titleInfo = (
    <Row>
      <div>
        <span>
          产品：{basicInfo.name}
        </span>
        <Badge style={{ marginLeft: 20 }} color={basicInfo.state === 1 ? 'green' : 'red'}
          text={basicInfo.state === 1 ? '已发布' : '未发布'} />
        {basicInfo.state === 1 ? (
          <Popconfirm title="确认停用？" onConfirm={() => {
            unDeploy(basicInfo);
          }}>
            <a style={{ fontSize: 12, marginLeft: 20 }}>停用</a>
          </Popconfirm>
        ) : (<Popconfirm title="确认发布？" onConfirm={() => {
          deploy(basicInfo);
        }}>
          <a style={{ fontSize: 12, marginLeft: 20 }}>发布</a>
        </Popconfirm>)}
      </div>
    </Row>
  );

  const action = (
    <Tooltip title="编辑产品信息后请重新应用配置">
      <Popconfirm title="确认重新应用该配置？" onConfirm={() => {
        deploy(basicInfo);
      }}>
        <Button icon="sync" type="primary">
          应用配置
        </Button>
      </Popconfirm>
    </Tooltip>
  );

  return (
    <Spin tip="加载中..." spinning={spinning}>
      <PageHeaderWrapper title={titleInfo}
        content={content}
        extra={action}
      >
        <Card>
          <Tabs>
            <Tabs.TabPane tab="产品信息" key="info">
              <Descriptions
                style={{ marginBottom: 20 }}
                bordered
                column={3}
                title={
                  <span>
                    产品信息
                    <Button
                      icon="edit"
                      style={{ marginLeft: 20 }}
                      type="link"
                      onClick={() => setSaveVisible(true)}
                    >
                      编辑
                    </Button>
                  </span>
                }
              >
                <Descriptions.Item label="产品ID" span={1}>
                  {basicInfo.id}
                </Descriptions.Item>
                {/*<Descriptions.Item label="产品名称" span={1}>
                  {basicInfo.name}
                </Descriptions.Item>*/}
                <Descriptions.Item label="所属品类" span={1}>
                  {basicInfo.classifiedName}
                </Descriptions.Item>
                <Descriptions.Item label="所属机构" span={1}>
                  {basicInfo.orgName}
                </Descriptions.Item>
                <Descriptions.Item label="消息协议" span={1}>
                  {basicInfo.protocolName || basicInfo.protocolId}
                </Descriptions.Item>
                <Descriptions.Item label="链接协议" span={1}>
                  {basicInfo.transportProtocol}
                </Descriptions.Item>
                <Descriptions.Item label="设备类型" span={1}>
                  {(basicInfo.deviceType || {}).text}
                </Descriptions.Item>
                <Descriptions.Item label="说明" span={3}>
                  {basicInfo.describe}
                </Descriptions.Item>
              </Descriptions>
              {config && config.length > 0 && (
                <div style={{ width: '100%' }}>
                  <Descriptions
                    title={
                      <span>
                        配置
                      <Button
                          icon="edit"
                          style={{ marginLeft: 20 }}
                          type="link"
                          onClick={() => setUpdateVisible(true)}
                        >
                          编辑
                    </Button>
                        {/* <Button
                          style={{ marginLeft: 10 }}
                          type="link"
                          onClick={() => setUpdateVisible(true)}
                        >
                          应用配置
                    </Button> */}
                      </span>
                    }
                  ></Descriptions>
                  {
                    config.map((i: any) => (
                      <div style={{ marginBottom: "20px" }} key={i.name}>
                        <h3>{i.name}</h3>
                        <Descriptions bordered column={2} title="">
                          {
                            i.properties && i.properties.map((item: any) => (
                              <Descriptions.Item label={item.description ? (<div><span style={{ marginRight: '10px' }}>{item.name}</span>
                                <Tooltip title={item.description}>
                                  <Icon type="question-circle-o" />
                                </Tooltip></div>) : item.name} span={1} key={item.property}>
                                {basicInfo.configuration ? (
                                  item.type.type === 'password' ? (
                                    basicInfo.configuration[item.property]?.length > 0 ? '••••••' : null
                                  ) :
                                    basicInfo.configuration[item.property]
                                ) : null}
                              </Descriptions.Item>
                            ))
                          }
                        </Descriptions>
                      </div>
                    ))
                  }
                </div>
              )}
            </Tabs.TabPane>
            <Tabs.TabPane tab="物模型" key="metadata">
              <Definition
                basicInfo={basicInfo}
                eventsData={events}
                functionsData={functions}
                propertyData={properties}
                tagsData={tags}
                unitsData={units}
                saveEvents={(data: any, onlySave: boolean) => {
                  setEvents(data);
                  updateData('event', data, onlySave);
                }}
                saveFunctions={(data: any, onlySave: boolean) => {
                  setFunctions(data);
                  updateData('function', data, onlySave);
                }}
                saveProperty={(data: any[], onlySave: boolean) => {
                  setProperties(data);
                  updateData('properties', data, onlySave);
                }}
                saveTags={(data: any[], onlySave: boolean) => {
                  setTags(data);
                  updateData('tags', data, onlySave);
                }}
                update={() => handleSearch(productId)}
              />
            </Tabs.TabPane>
            <Tabs.TabPane tab="告警设置" key="metadata1">
              <Alarm target="product" productId={basicInfo.id} productName={basicInfo.name} targetId={basicInfo.id}
                metaData={basicInfo.metadata}
                name={basicInfo.name} />
            </Tabs.TabPane>
          </Tabs>
        </Card>

        {saveVisible && (
          <Save
            data={basicInfo}
            close={() => setSaveVisible(false)}
            save={(item: any) => {
              setBasicInfo(item);
              saveData(item);
            }}
          />
        )}

        {updateVisible && (
          <Configuration
            data={basicInfo}
            configuration={config}
            close={() => {
              setUpdateVisible(false);
            }}
            save={(onlySave: boolean, item: any) => {
              updateInfo(onlySave, item);
            }}
          />
        )}
      </PageHeaderWrapper>
    </Spin>
  );
};
export default connect(({ deviceProduct, loading }: ConnectState) => ({
  deviceProduct,
  loading,
}))(Detail);

// src/views/pages/device/product/detail/index.vue
<template>
  <page-container :title="basicInfo.name">
    <template #content>
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <div>
          产品状态：<a-badge :color="basicInfo.state === 1 ? 'green' : 'red'" :text="basicInfo.state === 1 ? '已发布' : '未发布'"></a-badge>
          <template v-if="basicInfo.state === 1">
            <a-popconfirm title="确认停用？">
              <a style="margin-left: 20px">停用</a>
            </a-popconfirm>
          </template>
          <template v-else>
            <a style="margin-left: 20px">发布</a>
          </template>
        </div>
        <a-button type="primary"><SyncOutlined />应用配置</a-button>
      </div>
    </template>
    <a-card>
      <a-tabs tab-position="left">
        <a-tab-pane key="1" tab="产品信息">
          <a-descriptions bordered title="基本信息">
            <template #extra>
              <a-button type="primary" ghost @click="editBtn"><EditOutlined />编辑</a-button>
            </template>
            <a-descriptions-item label="产品ID">{{ basicInfo.id }}</a-descriptions-item>
            <a-descriptions-item label="产品名称">{{ basicInfo.name }}</a-descriptions-item>
            <a-descriptions-item label="所属品类">{{ basicInfo.classifiedName }}</a-descriptions-item>
            <a-descriptions-item label="消息协议">{{ basicInfo.messageProtocol }}</a-descriptions-item>
            <a-descriptions-item label="链接协议">{{ basicInfo.transportProtocol }}</a-descriptions-item>
            <a-descriptions-item label="设备类型">{{ basicInfo.deviceType.text }}</a-descriptions-item>
            <a-descriptions-item label="创建时间">{{ $moment(basicInfo.createTime).format('YYYY-MM-DD HH:mm:ss') }}</a-descriptions-item>
            <a-descriptions-item label="设备数量">
              <a>{{ basicInfo.count }}</a>
            </a-descriptions-item>
          </a-descriptions>
          <template v-if="(config || []).length > 0">
            <div style="margin-top: 20px">
              <div style="display: flex; justify-content: space-between;">
                <h3>配置</h3>
                <a-button @click="editConfig" type="primary" ghost><EditOutlined />编辑</a-button>
              </div>
              <template v-for="item in config" :key="item.name">
                <h3>{{ item.name }}</h3>
                <template v-if="item.properties">
                  <a-descriptions bordered :column="2">
                    <template v-for="i in item.properties" :key="i.property">
                      <a-descriptions-item :span="1">
                        <template #label>
                          {{ i.name }}<a-tooltip v-if="i.description" :title="i.description"><QuestionCircleOutlined /></a-tooltip>
                        </template>
                        <template v-if="basicInfo.configuration">
                          {{ i.type && i.type.type === 'password' && (basicInfo.configuration[i.property] || '').length > 0 ? '******' : basicInfo.configuration[i.property] }}
                        </template>
                      </a-descriptions-item>
                    </template>
                  </a-descriptions>
                </template>
              </template>
            </div>
          </template>
        </a-tab-pane>
        <a-tab-pane key="2" tab="物模型">
          <Definition />
        </a-tab-pane>
        <a-tab-pane key="3" tab="告警设置">
          <Alarm :target="'product'" :targetId="id" />
        </a-tab-pane>
      </a-tabs>
    </a-card>
    <Save v-model="visible" :data="basicInfo" @ok-btn="okBtn" />
  </page-container>
  <Configuration @ok-btn="saveConfig" v-model="updateVisible" :data="basicInfo" :configuration="config" />
</template>
<script lang="ts">
import { defineComponent, onMounted, reactive, ref, provide } from 'vue'
import { getProductDetail, getDeviceCount, productConfiguration, updateProduct, setUnDeploy } from '@/views/pages/device/product/service'
import encodeQuery from '@/utils/encodeQuery'
import { service } from '@/views/pages/device/product/index.vue'
import Save from '../save/index.vue'
import Definition from './definition/index.vue'
import Alarm from '../../alarm/index.vue'
import Configuration from './configuration/index.vue'
import { message } from 'ant-design-vue'
export type ProductItem = {
  id: string;
  name: string;
  classifiedId: string;
  classifiedName: string;
  configuration?: Record<string, any>;
  createTime?: number;
  creatorId?: string;
  deviceType: {
    text: string;
    value: string;
  };
  photoUrl?: string;
  count?: number;
  messageProtocol: string;
  metadata: string;
  orgId: string;
  protocolName: string;
  state?: number;
  transportProtocol: string;
}
export default defineComponent({
  props: ['id'],
  components: { Save, Definition, Alarm, Configuration },
  setup (props) {
    const id = props.id || ''
    const visible = ref<boolean>(false)
    const updateVisible = ref<boolean>(false)
    const basicInfo = reactive<ProductItem>({
      id: '',
      name: '',
      classifiedId: '',
      classifiedName: '',
      photoUrl: 'https://demo.jetlinks.cn/static/product.1bd0a3b1.png',
      deviceType: {
        text: '',
        value: ''
      },
      messageProtocol: '',
      orgId: '',
      protocolName: '',
      transportProtocol: '',
      metadata: '{"events":[],"properties":[],"functions":[],"tags":[]}'
    })
    provide('basicInfo', basicInfo)
    const config = ref<any>()
    const getBasicInfo = () => {
      getProductDetail(id).then(resp => {
        if (resp.data.status === 200) {
          Object.assign(basicInfo, resp.data.result)
          getDeviceCount(encodeQuery({
            terms: {
              productId: resp.data.result.id
            }
          })).then(resp => {
            if (resp.data.status === 200) {
              basicInfo.count = resp.data.result
            }
          })
          productConfiguration(resp.data.result.id).then(resp => {
            if (resp.data.status === 200) {
              config.value = resp.data.result
            }
          })
        }
      })
    }
    onMounted(() => {
      getBasicInfo()
    })
    const editBtn = () => {
      visible.value = true
    }
    const okBtn = (data: any) => {
      service.update(data).then(resp => {
        if (resp.data.status === 200) {
          getBasicInfo()
        }
        visible.value = false
      })
    }
    const editConfig = () => {
      updateVisible.value = true
    }
    const saveConfig = (data: any) => {
      const params = { configuration: { ...data.configuration } }
      updateProduct(id, params).then(resp => {
        if (resp.data.status === 200) {
          if (!data.onlySave) {
            setUnDeploy(id || '').then(res => {
              if (res.data.status === 200) {
                message.success('操作成功')
                getBasicInfo()
              }
            })
          } else {
            getBasicInfo()
          }
        }
        updateVisible.value = false
      })
    }
    return {
      visible,
      basicInfo,
      editBtn,
      okBtn,
      config,
      updateVisible,
      editConfig,
      saveConfig
    }
  }
})
</script>
