// src/pages/system/tenant/index.tsx
import { PageHeaderWrapper } from "@ant-design/pro-layout"
import React, { useState, useEffect } from "react"
import { Card, Button, List, Radio, Input, Avatar, Tag, message, Spin, Popconfirm } from "antd";
import { PlusOutlined } from "@ant-design/icons";
import moment from "moment";
import { ListData } from "@/services/response";
import { router } from "umi";
import defaultImg from '@/assets/default.png';
import { TenantItem } from "./data";
import styles from './index.less';
import Service from "./service";
import Save from "./save";
import { PaginationConfig } from "antd/lib/pagination";
import encodeQueryParam from "@/utils/encodeParam";

const RadioButton = Radio.Button;
const RadioGroup = Radio.Group;
const { Search } = Input;


const ListContent = ({
    data: { members, state, createTime },
}: {
    data: TenantItem;
}) => (
        <div className={styles.listContent}>
            <div className={styles.listContentItem}>
                <span>状态</span>
                <p><Tag color={state.value === 'enabled' ? '#87d068' : '#F50'}>{state.text}</Tag></p>
            </div>
            <div className={styles.listContentItem}>
                <span>成员数</span>
                <p><Tag color="#87d068">{members}</Tag></p>
            </div>
            <div className={styles.listContentItem}>
                <span>创建时间</span>
                <p>{moment(createTime).format('YYYY-MM-DD HH:mm')}</p>
            </div>
        </div>
    );


const Tenant = () => {

    const service = new Service('tenant');
    const [loading, setLoading] = useState<boolean>(false);
    const [tloading, setTloading] = useState<boolean>(false);
    const [visible, setVisible] = useState<boolean>(false);
    const [current, setCurrent] = useState<Partial<TenantItem>>({});
    const [list, setList] = useState<ListData<TenantItem>>();
    const [searchParam, setSearchParam] = useState({});


    const handleSearch = (params: any) => {
        setTloading(true);
        setSearchParam(params);
        service.list(params).subscribe(data => {
            setList(data);
            setTloading(false);
        });
    }

    useEffect(() => {
        handleSearch({})
    }, []);


    const paginationProps: PaginationConfig = {
        showQuickJumper: true,
        pageSize: 5,
        total: list?.total || 0,
        onChange: page => handleSearch({ pageIndex: page - 1, pageSize: 5 }),
    };

    const extraContent = (
        <div className={styles.extraContent}>
            <RadioGroup defaultValue="all" onChange={(e) => handleSearch(encodeQueryParam({ terms: { state: e.target.value } }))}>
                <RadioButton value="">全部</RadioButton>
                <RadioButton value="enabled">正常</RadioButton>
                <RadioButton value="disabled">禁用</RadioButton>
            </RadioGroup>
            {/* <Search className={styles.extraContentSearch} placeholder="请输入" onSearch={() => ({})} /> */}
        </div>
    );

    const saveItem = (data: any) => {
        setLoading(true);
        service.create(data).subscribe(() => {
            message.success('保存成功');
            setLoading(false);
            setVisible(false);
            setCurrent({});
            handleSearch(searchParam);
        });
    }

    const changeState = (item: any, state: string) => {
        setLoading(true);
        const data = item;
        data.state = state;
        service.update(data).subscribe(() => {
            setLoading(false);
            message.success('操作成功');
            handleSearch(searchParam);
        });
    }

    return (
        <PageHeaderWrapper>
            <Spin spinning={tloading}>
                <div className={styles.standardList}>
                    <Card
                        className={styles.listCard}
                        bordered={false}
                        title="租户列表"
                        style={{ marginTop: 24 }}
                        bodyStyle={{ padding: '0 32px 40px 32px' }}
                        extra={extraContent}
                    >
                        <Button
                            type="dashed"
                            style={{ width: '100%', marginBottom: 8 }}
                            onClick={() => {
                                setVisible(true);
                                setCurrent({});
                            }}
                        >
                            <PlusOutlined />
                     添加
                    </Button>

                        <List
                            size="large"
                            rowKey="id"
                            pagination={paginationProps}
                            dataSource={list?.data}
                            renderItem={(item: TenantItem) => (
                                <List.Item
                                    actions={[
                                        <a onClick={e => {
                                            e.preventDefault();
                                            router.push(`/system/tenant/detail/${item.id}`)
                                        }}>查看</a>,
                                        <>
                                            {
                                                item.state.value === 'enabled' ?
                                                    (
                                                        <Popconfirm title="确认禁用此租户？"
                                                            onConfirm={() => {
                                                                changeState(item, 'disabled');
                                                            }}>
                                                            <a key="edit">
                                                                禁用
                                                            </a>
                                                        </Popconfirm>) :
                                                    (
                                                        <Popconfirm title="确认禁用此租户？"
                                                            onConfirm={() => {
                                                                changeState(item, 'enabled');
                                                            }}>
                                                            <a key="edit">
                                                                启用
                                                            </a>
                                                        </Popconfirm>
                                                    )
                                            }
                                        </>,
                                    ]}
                                >
                                    <List.Item.Meta
                                        avatar={<Avatar src={item.photo || defaultImg} shape="square" size="large" />}
                                        title={<a >{item.name}</a>}
                                        description={item.description}
                                    />
                                    <ListContent data={item} />
                                </List.Item>
                            )}
                        />
                    </Card>
                </div>
            </Spin>

            {visible && (
                <Spin spinning={loading}>
                    <Save
                        close={() => { setVisible(false) }}
                        save={(item: any) => saveItem(item)}
                        data={current}
                    />
                </Spin>
            )}
        </PageHeaderWrapper>
    )
}
export default Tenant;

// src/views/pages/system/tenant/index.vue
<template>
  <page-container title="租户管理">
    <BaseCrud :form-data="{}" @modal-visible="modalVisible" :model="model" :columns="columns" title="租户列表" :service="service" :default-params="defaultParams">
      <template #extra>
        <a-space>
          <a-button @click="addBtn" type="primary">新增</a-button>
        </a-space>
      </template>
      <template #name="{ record }">
        <a-avatar shape="square" :size="32" :src="record.tenant.photo"></a-avatar>
        <span style="margin-left: 10px;">{{ record.tenant.name }}</span>
      </template>
      <template #state="{ record }">
        <template v-if="record.tenant.state.value === 'enabled'">
          <a-tag color="#108ee9">{{ record.tenant.state.text }}</a-tag>
        </template>
        <template v-else>
          <a-tag color="#f50">{{ record.tenant.state.text }}</a-tag>
        </template>
      </template>
      <template #createTime="{ record }">
        <span>{{ $moment(record.tenant.createTime).format('YYYY-MM-DD HH:mm:ss') }}</span>
      </template>
      <template #action="{ record }">
        <a-space>
          <a>查看</a>
          <template v-if="record.tenant.state.value === 'enabled'">
            <a-popconfirm
              title="确认禁用?"
              ok-text="确认"
              cancel-text="取消"
              @confirm="changeState(record, 'disabled')"
            >
              <a>禁用</a>
            </a-popconfirm>
          </template>
          <template v-else>
            <a-popconfirm
              title="确认启用?"
              ok-text="确认"
              cancel-text="取消"
              @confirm="changeState(record, 'enabled')"
            >
              <a>启用</a>
            </a-popconfirm>
          </template>
        </a-space>
      </template>
    </BaseCrud>
  </page-container>
  <a-modal :width="500" title="新增租户" v-model:visible="visible" cancelText="取消" okText="确认" @ok="okBtn" @cancel="cancelBtn">
    <a-form :model="form" :rules="rules" layout="vertical">
      <a-form-item label="头像" name="photo">
        <FormUpload v-model="form.photo" />
      </a-form-item>
      <a-form-item label="名称" name="name">
        <a-input v-model:value="form.name" placeholder="请输入" />
      </a-form-item>
      <a-form-item label="用户名" name="username">
        <a-input v-model:value="form.username" placeholder="请输入"
        />
      </a-form-item>
      <a-form-item label="新密码" name="password">
        <a-input type="password" v-model:value="form.password" placeholder="请输入" />
      </a-form-item>
      <a-form-item label="确认密码" name="confirmPassword">
        <a-input type="password" v-model:value="form.confirmPassword" placeholder="请输入" />
      </a-form-item>
      <a-form-item label="描述" name="description">
        <a-textarea
          v-model:value="form.description"
          :rows="4"
          placeholder="请输入"
        />
      </a-form-item>
    </a-form>
  </a-modal>
</template>

<script lang="ts">
import { defineComponent, reactive, ref } from 'vue'
import BaseCrud from '@/components/BaseCrud/index.vue'
import FormUpload from '@/components/FormUpload/index.vue'
import BaseService from '@/utils/base-service'
import { createTenant, updateTenant } from './service'
import { message } from 'ant-design-vue'
type State = {
  value: string;
  text: string;
}
export type TenantDetail = {
  id: string;
  name: string;
  type: string;
  state: State;
  members: number;
  photo: string;
  createTime: number;
  description: string;
}

export type TenantItem = {
  members: number;
  tenant: Partial<TenantDetail>;
}

export default defineComponent({
  components: {
    BaseCrud,
    FormUpload
  },
  setup () {
    const service = new BaseService<TenantItem>('tenant/detail')
    const columns = [
      {
        title: '名称',
        dataIndex: 'name',
        key: 'name',
        slots: true
      },
      {
        title: '状态',
        dataIndex: 'state',
        align: 'center',
        key: 'state',
        slots: true
      },
      {
        title: '成员数量',
        align: 'center',
        dataIndex: 'members',
        key: 'members'
      },
      {
        title: '创建时间',
        dataIndex: 'createTime',
        key: 'createTime',
        align: 'center',
        slots: true
      },
      {
        title: '操作',
        dataIndex: 'action',
        key: 'action',
        align: 'center',
        slots: true
      }
    ]
    const model = ref<'edit' | 'preview' | 'add' | 'refresh'>('preview')
    const defaultParams = {
      pageIndex: 0,
      pageSize: 10,
      sorts: {
        id: 'desc'
      }
    }
    const visible = ref<boolean>(false)
    const form = reactive({
      name: '',
      username: '',
      photo: '',
      description: '',
      confirmPassword: '',
      password: ''
    })
    const rules = {
      name: [{ required: true, message: '请输入' }],
      username: [{ required: true, message: '请输入' }],
      confirmPassword: [{ required: true, message: '请输入' }],
      password: [{ required: true, message: '请输入' }]
    }
    const modalVisible = (value: 'edit' | 'preview' | 'add' | 'refresh') => {
      model.value = value
    }
    const addBtn = () => {
      visible.value = true
    }
    const initValue = () => {
      form.name = ''
      form.username = ''
      form.photo = ''
      form.description = ''
      form.confirmPassword = ''
      form.password = ''
    }
    const cancelBtn = () => {
      initValue()
      visible.value = false
    }
    const okBtn = () => {
      model.value = 'preview'
      createTenant(form).then(resp => {
        if (resp.data.status === 200) {
          message.success('操作成功！')
          model.value = 'refresh'
        }
        cancelBtn()
      })
    }
    const changeState = (data: any, state: string) => {
      const params = data.tenant
      params.state = state
      model.value = 'preview'
      updateTenant(params).then(resp => {
        if (resp.data.status === 200) {
          message.success('操作成功！')
          model.value = 'refresh'
        }
      })
    }
    return {
      columns,
      service,
      defaultParams,
      model,
      addBtn,
      modalVisible,
      form,
      visible,
      okBtn,
      cancelBtn,
      rules,
      changeState
    }
  }
})
</script>
